'\" t
.\"     Title: chgpasswd
.\"    Author: Thomas K\(/loczko <kloczek@pld.org.pl>
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/11/2022
.\"    Manual: Команди керування системою
.\"    Source: shadow-utils 4.13
.\"  Language: Ukrainian
.\"
.TH "chgpasswd" "8" "08/11/2022" "shadow\-utils 4\&.13" "Команди керування системою"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
chgpasswd \- оновлення паролів груп у пакетному режимі
.SH "КОРОТКИЙ ОГЛЯД"
.HP \w'\fBchgpasswd\fR\ 'u
\fBchgpasswd\fR [\fIпараметри\fR]
.SH "ОПИС"
.PP
Команда
\fBchgpasswd\fR
читає список пар назва групи \(em пароль зі стандартного джерела вхідних даних і використовує ці дані для оновлення набору наявних груп\&. Кожен рядок записується у такому форматі:
.PP
\fIназва_групи\fR:\fIпароль\fR
.PP
Типово, наданий пароль має бути простим текстовим\&. Його буде зашифровано за допомогою
\fBchgpasswd\fR\&.
.PP
Типовий алгоритм шифрування може бути визначено для системи за допомогою змінної
\fBENCRYPT_METHOD\fR
у
/etc/login\&.defs, і може бути перезаписано за допомогою параметрів
\fB\-e\fR,
\fB\-m\fR
або
\fB\-c\fR\&.
.PP
Цю команду призначено для використання у великих системних середовищах, де одночасно створюють багато облікових записів\&.
.SH "ПАРАМЕТРИ"
.PP
Параметри, які застосовують до команди
\fBchgpasswd\fR, є такими:
.PP
\fB\-c\fR, \fB\-\-crypt\-method\fR
.RS 4
Скористатися для шифрування паролів вказаним методом\&.
.sp
Доступними методами є DES, MD5, NONE і SHA256 або SHA512, якщо у вашій libc передбачено підтримку цих методів\&.
.RE
.PP
\fB\-e\fR, \fB\-\-encrypted\fR
.RS 4
Надані паролі подано у зашифрованій формі\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показати довідкове повідомлення і завершити роботу\&.
.RE
.PP
\fB\-m\fR, \fB\-\-md5\fR
.RS 4
Скористатися шифруванням MD5 замість DES, якщо надані паролі не зашифровано\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR \fIКАТАЛОГ_CHROOT\fR
.RS 4
Apply changes in the
\fICHROOT_DIR\fR
directory and use the configuration files from the
\fICHROOT_DIR\fR
directory\&. Only absolute paths are supported\&.
.RE
.PP
\fB\-s\fR, \fB\-\-sha\-rounds\fR
.RS 4
Використати вказану кількість циклів шифрування паролів\&.
.sp
Значення 0 означає, що система вибере типову кількість проходів для методу шифрування (5000)\&.
.sp
Буде примусово встановлено мінімальне значення 1000 і максимальне значення 999999999\&.
.sp
Ви можете скористатися цим параметром у поєднанні із методами шифрування SHA256 або SHA512\&.
.sp
Типово, кількість проходів визначається за допомогою змінних SHA_CRYPT_MIN_ROUNDS і SHA_CRYPT_MAX_ROUNDS у
/etc/login\&.defs\&.
.RE
.SH "ЗАСТЕРЕЖЕННЯ"
.PP
Не забудьте встановити права доступу або umask, щоб запобігти доступності до читання нешифрованих файлів сторонніми користувачами\&.
.PP
Вам слід переконатися, що паролі і метод шифрування відповідає правилам поводження з паролями у системі\&.
.SH "НАЛАШТУВАННЯ"
.PP
Вказані нижче змінні налаштувань у
/etc/login\&.defs
змінюють поведінку цього інструмента:
.SH "ФАЙЛИ"
.PP
/etc/group
.RS 4
Відомості щодо груп облікових записів\&.
.RE
.PP
/etc/gshadow
.RS 4
Відомості щодо захищених груп облікових записів\&.
.RE
.PP
/etc/login\&.defs
.RS 4
Налаштування комплексу для роботи з прихованими паролями\&.
.RE
.SH "ДИВ\&. ТАКОЖ"
.PP
\fBgpasswd\fR(1),
\fBgroupadd\fR(8),
\fBlogin.defs\fR(5)\&.
