'\" t
.\"     Title: faillog
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/11/2022
.\"    Manual: Команди керування системою
.\"    Source: shadow-utils 4.13
.\"  Language: Ukrainian
.\"
.TH "faillog" "8" "08/11/2022" "shadow\-utils 4\&.13" "Команди керування системою"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
faillog \- вивести записи faillog або встановити обмеження на невдалі спроби увійти до системи
.SH "КОРОТКИЙ ОГЛЯД"
.HP \w'\fBfaillog\fR\ 'u
\fBfaillog\fR [\fIпараметри\fR]
.SH "ОПИС"
.PP
\fBfaillog\fR
показує вміст бази даних помилок під час входу до системи (/var/log/faillog)\&. Ця програма також може встановлювати лічильник і обмеження помилок\&. Якщо
\fBfaillog\fR
запущено без аргументів, програма покаже лише записи користувачів, при спробах входу до системи яких сталася помилка\&.
.SH "ПАРАМЕТРИ"
.PP
Параметри, які застосовують до команди
\fBfaillog\fR, є такими:
.PP
\fB\-a\fR, \fB\-\-all\fR
.RS 4
Вивести (або виконати дію) над записами faillog для усіх користувачів, запис яких міститься у базі даних
faillog\&.
.sp
Діапазон учасників можна обмежити за допомогою параметра
\fB\-u\fR\&.
.sp
У режимі показу діапазон буде обмежено наявними користувачами, але буде примусово показано записи faillog, навіть якщо вони є порожніми\&.
.sp
З параметрами
\fB\-l\fR,
\fB\-m\fR,
\fB\-r\fR,
\fB\-t\fR
записи користувачів буде змінено, навіть якщо запису користувача не існує у системі\&. Це корисно для скидання записів користувачів, облікові записи яких було вилучено, або встановлення наперед правил для діапазону користувачів\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показати довідкове повідомлення і завершити роботу\&.
.RE
.PP
\fB\-l\fR, \fB\-\-lock\-secs\fR \fIСЕК\fR
.RS 4
Заблокувати обліковий запис на
\fIСЕК\fR
секунд після невдалої спроби увійти до системи\&.
.sp
Для користування цим параметром потрібен доступ до запису для файла
/var/log/faillog\&.
.RE
.PP
\fB\-m\fR, \fB\-\-maximum\fR \fIМАКСИМУМ\fR
.RS 4
Встановити максимальну кількість невдалих спроб, після якої обліковий запис буде вимкнено, у значення
\fIМАКСИМУМ\fR\&.
.sp
Вибір для
\fIМАКСИМУМ\fR
значення 0 призведе до усування обмеження на кількість невдалих спроб увійти до системи\&.
.sp
Для
\fIroot\fR
максимальною кількістю невдалих спроб увійти до системи має завжди бути 0, щоб запобігти спробам атакувати систему, викликавши відмову в обслуговуванні\&.
.sp
Для користування цим параметром потрібен доступ до запису для файла
/var/log/faillog\&.
.RE
.PP
\fB\-r\fR, \fB\-\-reset\fR
.RS 4
Скинути лічильники помилок входу\&.
.sp
Для користування цим параметром потрібен доступ до запису для файла
/var/log/faillog\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR \fIКАТАЛОГ_CHROOT\fR
.RS 4
Apply changes in the
\fICHROOT_DIR\fR
directory and use the configuration files from the
\fICHROOT_DIR\fR
directory\&. Only absolute paths are supported\&.
.RE
.PP
\fB\-t\fR, \fB\-\-time\fR \fIДНІ\fR
.RS 4
Показати записи faillog, які є свіжішими за
\fIДНІ\fR\&.
.RE
.PP
\fB\-u\fR, \fB\-\-user\fR \fIЗАПИС\fR|\fIДІАПАЗОН\fR
.RS 4
Вивести запис журналу помилок або лічильників помилок і обмежень на помилки (якщо використано з
\fB\-l\fR,
\fB\-m\fR
або
\fB\-r\fR) лише для вказаних користувачів\&.
.sp
Користувачів можна задавати за обліковим записом для входу, числовим ідентифікатором користувача або значенням
\fIДІАПАЗОН\fR
для користувачів\&.
\fIДІАПАЗОН\fR
користувачів можна вказати за допомогою мінімального і максимального значень (\fIUID_MIN\-UID_MAX\fR), максимального значення (\fI\-UID_MAX\fR) або мінімального значення (\fIUID_MIN\-\fR)\&.
.RE
.PP
Якщо не вказано жодного з параметрів
\fB\-l\fR,
\fB\-m\fR
або
\fB\-r\fR,
\fBfaillog\fR
показує запис faillog вказаних користувачів\&.
.SH "ЗАСТЕРЕЖЕННЯ"
.PP
\fBfaillog\fR
виводить дані лише користувачів, які не мали успішних входів до системи з моменту останньої помилки\&. Щоб було виведено запис користувача, який успішно входив до системи з часу останньої помилки, вам слід явним чином надіслати запит щодо користувача за допомогою прапорця
\fB\-u\fR
або наказати програмі вивести дані усіх користувачів за допомогою прапорця
\fB\-a\fR\&.
.SH "ФАЙЛИ"
.PP
/var/log/faillog
.RS 4
Файл журналу помилок\&.
.RE
.SH "ДИВ\&. ТАКОЖ"
.PP
\fBlogin\fR(1),
\fBfaillog\fR(5)\&.
