'\" t
.\"     Title: groupdel
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/11/2022
.\"    Manual: Команди керування системою
.\"    Source: shadow-utils 4.13
.\"  Language: Ukrainian
.\"
.TH "groupdel" "8" "08/11/2022" "shadow\-utils 4\&.13" "Команди керування системою"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
groupdel \- вилучення групи
.SH "КОРОТКИЙ ОГЛЯД"
.HP \w'\fBgroupdel\fR\ 'u
\fBgroupdel\fR [\fIпараметри\fR] \fIGROUP\fR
.SH "ОПИС"
.PP
Команда
\fBgroupdel\fR
вносить зміни до файлів загальносистемних облікових записів, вилучаючи усі записи, які стосуються імені користувача\fIGROUP\fR\&. Іменована група має існувати\&.
.SH "ПАРАМЕТРИ"
.PP
Параметри, які застосовують до команди
\fBgroupdel\fR, є такими:
.PP
\fB\-f\fR, \fB\-\-force\fR
.RS 4
Використання цього параметра призведе до вилучення групи, навіть якщо лишається якийсь користувач, для якого ця група є основною\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показати довідкове повідомлення і завершити роботу\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR \fIКАТАЛОГ_CHROOT\fR
.RS 4
Apply changes in the
\fICHROOT_DIR\fR
directory and use the configuration files from the
\fICHROOT_DIR\fR
directory\&. Only absolute paths are supported\&.
.RE
.PP
\fB\-P\fR, \fB\-\-prefix\fR \fIКАТАЛОГ_ПРЕФІКСА\fR
.RS 4
Застосувати зміни до каталогу
\fIКАТАЛОГ_ПРЕФІКСА\fR
і використати файли налаштувань з каталогу
\fIКАТАЛОГ_ПРЕФІКСА\fR\&. Використання цього параметра не змінює кореневої теки\&. Параметр призначено лише для приготування цілі для компіляції коду для іншої операційної системи\&. Обмеження: не буде виконано перевірку користувачів/груп NIS і LDAP\&. При розпізнаванні у PAM буде використано файли основної системи\&. Підтримки SELINUX не передбачено\&.
.RE
.SH "ЗАСТЕРЕЖЕННЯ"
.PP
Ви не можете вилучити основну групу будь\-якого наявного користувача\&. Вам слід вилучити запис користувача, перш ніж вилучати його основну групу\&.
.PP
Вам слід виконати перевірку усіх файлових систем вручну, щоб переконатися, щоб не лишилося жодних файлів, які належать цій групі\&.
.SH "НАЛАШТУВАННЯ"
.PP
Вказані нижче змінні налаштувань у
/etc/login\&.defs
змінюють поведінку цього інструмента:
.SH "ФАЙЛИ"
.PP
/etc/group
.RS 4
Відомості щодо груп облікових записів\&.
.RE
.PP
/etc/gshadow
.RS 4
Відомості щодо захищених груп облікових записів\&.
.RE
.SH "ЗНАЧЕННЯ ВИХОДУ"
.PP
Команда
\fBgroupdel\fR
завершує роботу із такими значеннями:
.PP
\fI0\fR
.RS 4
успіх
.RE
.PP
\fI2\fR
.RS 4
некоректний синтаксис команди
.RE
.PP
\fI6\fR
.RS 4
вказаної групи не існує
.RE
.PP
\fI8\fR
.RS 4
не вдалося вилучити основну групу користувача
.RE
.PP
\fI10\fR
.RS 4
не вдалося оновити файл груп
.RE
.SH "ДИВ\&. ТАКОЖ"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBgpasswd\fR(8),
\fBgroupadd\fR(8),
\fBgroupmod\fR(8),
\fBuseradd\fR(8),
\fBuserdel\fR(8),
\fBusermod\fR(8)\&.
