'\" t
.\"     Title: groupadd
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/11/2022
.\"    Manual: Команди керування системою
.\"    Source: shadow-utils 4.13
.\"  Language: Ukrainian
.\"
.TH "groupadd" "8" "08/11/2022" "shadow\-utils 4\&.13" "Команди керування системою"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
groupadd \- створення нової групи
.SH "КОРОТКИЙ ОГЛЯД"
.HP \w'\fBgroupadd\fR\ 'u
\fBgroupadd\fR [\fIПАРАМЕТРИ\fR] \fIНОВА_ГРУПА\fR
.SH "ОПИС"
.PP
Команда
\fBgroupadd\fR
створює обліковий запис групи з використанням значень, які вказано у командному рядку, і типових для системи значень\&. Запис нової групи буде додано до файлів системи, якщо у цьому буде потреба\&.
.PP
Groupnames may contain only lower and upper case letters, digits, underscores, or dashes\&. They can end with a dollar sign\&. Dashes are not allowed at the beginning of the groupname\&. Fully numeric groupnames and groupnames \&. or \&.\&. are also disallowed\&.
.PP
Довжина назв груп не може перевищувати 32 символи\&.
.SH "ПАРАМЕТРИ"
.PP
Параметри, які застосовують до команди
\fBgroupadd\fR, є такими:
.PP
\fB\-f\fR, \fB\-\-force\fR
.RS 4
Використання цього параметра призведе до простого виходу з команди зі станом успіху, якщо вказана група вже існує\&. Якщо використано разом із
\fB\-g\fR, і вказаний GID вже існує, буде вибрано інший (унікальний) GID (тобто буде вимкнено
\fB\-g\fR)\&.
.RE
.PP
\fB\-g\fR, \fB\-\-gid\fR \fIGID\fR
.RS 4
Числове значення ідентифікатора групи\&.
\fIGID\fR
має бути унікальним, якщо не використано параметр
\fB\-o\fR\&. Значення має бути невід\*(Aqємним\&. Типовим є використання найменшого значення ідентифікатора, яке дорівнює або перевищує
\fBМІНІМАЛЬНИЙ_GID\fR
і є більшим за значення ідентифікатора будь\-якої іншої групи\&.
.sp
Див\&. також описи параметрів
\fB\-r\fR
і
\fBМАКСИМАЛЬНИЙ_GID\fR\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показати довідкове повідомлення і завершити роботу\&.
.RE
.PP
\fB\-K\fR, \fB\-\-key\fR \fIКЛЮЧ\fR=\fIЗНАЧЕННЯ\fR
.RS 4
Має пріоритет над типовими значенням у
/etc/login\&.defs
(GID_MIN, GID_MAX та іншими)\&. Може бути вказано декілька параметрів
\fB\-K\fR\&.
.sp
Приклад:
\fB\-K\fR
\fIМІНІМАЛЬНИЙ_GID\fR=\fI100\fR
\fB\-K\fR
\fIМАКСИМАЛЬНИЙ_GID\fR=\fI499\fR
.sp
Зауваження:
\fB\-K\fR
\fIМІНІМАЛЬНИЙ_GID\fR=\fI10\fR,\fIМАКСИМАЛЬНИЙ_GID\fR=\fI499\fR
ще не працює\&.
.RE
.PP
\fB\-o\fR, \fB\-\-non\-unique\fR
.RS 4
уможливлює створення груп із вже використаним числовим ідентифікатором\&. У результаті для цього
\fIGID\fR
прив\*(Aqязка до групи
\fIНОВА_ГРУПА\fR
може бути неунікальною\&.
.RE
.PP
\fB\-p\fR, \fB\-\-password\fR \fIПАРОЛЬ\fR
.RS 4
визначає початковий пароль до облікового запису групи\&. ПАРОЛЬ має бути зашифровано у форматі, який повертає
\fBcrypt\fR(3)\&.
.sp
Без цього параметра обліковий запис групи буде заблоковано; для нього також не буде визначено пароля, тобто у відповідному полі файла облікових записів системи
/etc/group
або
/etc/gshadow
буде вказано одинарний знак оклику\&.
.sp
\fBЗауваження:\fR
не рекомендуємо користуватися цим параметром, оскільки пароль (або шифрований пароль) буде видимим для користувачів, які мають доступ до списку процесів\&.
.sp
Вам слід переконатися, що пароль відповідає правилам складання паролів системи\&.
.RE
.PP
\fB\-r\fR, \fB\-\-system\fR
.RS 4
Створити загальносистемну групу\&.
.sp
Числові ідентифікатори нових груп системи буде вибрано у діапазоні
\fBSYS_GID_MIN\fR\-\fBSYS_GID_MAX\fR
range, defined in
login\&.defs, замість діапазону
\fBМІНІМАЛЬНИЙ_GID\fR\-\fBМАКСИМАЛЬНИЙ_GID\fR\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR \fIКАТАЛОГ_CHROOT\fR
.RS 4
Apply changes in the
\fICHROOT_DIR\fR
directory and use the configuration files from the
\fICHROOT_DIR\fR
directory\&. Only absolute paths are supported\&.
.RE
.PP
\fB\-P\fR, \fB\-\-prefix\fR \fIКАТАЛОГ_ПРЕФІКСА\fR
.RS 4
Застосувати зміни до файлів налаштувань у кореневій файловій системі з каталогу
\fIКАТАЛОГ_ПРЕФІКСА\fR\&. Використання цього параметра не змінює кореневої теки\&. Параметр призначено лише для приготування цілі для компіляції коду для іншої операційної системи\&. Обмеження: не буде виконано перевірку користувачів/груп NIS і LDAP\&. При розпізнаванні у PAM буде використано файли основної системи\&. Підтримки SELINUX не передбачено\&.
.RE
.PP
\fB\-U\fR, \fB\-\-users\fR
.RS 4
Список імен користувачів, яких слід додати як учасників групи\&.
.sp
Типову поведінку (якщо не вказано параметрів
\fB\-g\fR,
\fB\-N\fR
і
\fB\-U\fR) буде визначено змінною
\fBUSERGROUPS_ENAB\fR
у
/etc/login\&.defs\&.
.RE
.SH "НАЛАШТУВАННЯ"
.PP
Вказані нижче змінні налаштувань у
/etc/login\&.defs
змінюють поведінку цього інструмента:
.SH "ФАЙЛИ"
.PP
/etc/group
.RS 4
Відомості щодо груп облікових записів\&.
.RE
.PP
/etc/gshadow
.RS 4
Відомості щодо захищених груп облікових записів\&.
.RE
.PP
/etc/login\&.defs
.RS 4
Налаштування комплексу для роботи з прихованими паролями\&.
.RE
.SH "ЗАСТЕРЕЖЕННЯ"
.PP
Не можна додавати групи NIS або LDAP\&. Для таких груп цю дію має бути виконано на відповідному сервері\&.
.PP
Якщо назва групи вже існує у зовнішній базі даних груп, зокрема NIS або LDAP,
\fBgroupadd\fR
відмовить у запиті щодо створення групи\&.
.SH "ЗНАЧЕННЯ ВИХОДУ"
.PP
Команда
\fBgroupadd\fR
завершує роботу із такими значеннями:
.PP
\fI0\fR
.RS 4
успіх
.RE
.PP
\fI2\fR
.RS 4
некоректний синтаксис команди
.RE
.PP
\fI3\fR
.RS 4
некоректний аргумент параметра
.RE
.PP
\fI4\fR
.RS 4
GID вже використано (якщо викликано без
\fB\-o\fR)
.RE
.PP
\fI9\fR
.RS 4
назву групи вже використано
.RE
.PP
\fI10\fR
.RS 4
не вдалося оновити файл груп
.RE
.SH "ДИВ\&. ТАКОЖ"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBgpasswd\fR(8),
\fBgroupdel\fR(8),
\fBgroupmod\fR(8),
\fBlogin.defs\fR(5),
\fBuseradd\fR(8),
\fBuserdel\fR(8),
\fBusermod\fR(8)\&.
