'\" t
.\"     Title: groupmems
.\"    Author: George Kraft, IV
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/11/2022
.\"    Manual: Команди керування системою
.\"    Source: shadow-utils 4.13
.\"  Language: Ukrainian
.\"
.TH "groupmems" "8" "08/11/2022" "shadow\-utils 4\&.13" "Команди керування системою"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
groupmems \- адміністрування учасників основної групи користувача
.SH "КОРОТКИЙ ОГЛЯД"
.HP \w'\fBgroupmems\fR\ 'u
\fBgroupmems\fR \-a\ \fIім\*(Aqя_користувача\fR | \-d\ \fIім\*(Aqя_користувача\fR | [\-g\ \fIназва_групи\fR] | \-l | \-p 
.SH "ОПИС"
.PP
Команда
\fBgroupmems\fR
надає змогу користувачеві адмініструвати список учасників власної групи без потреби у привілеях надкористувача\&. Допоміжну програму
\fBgroupmems\fR
призначено для систем, у яких облікові запис користувачів налаштовують так, щоб основною групою для них була група із назвою, яка збігається із назвою облікового запису користувача (тобто guest / guest)\&.
.PP
Лише надкористувач, як адміністратор, може використовувати
\fBgroupmems\fR
для зміни учасників інших груп\&.
.SH "ПАРАМЕТРИ"
.PP
Параметри, які застосовують до команди
\fBgroupmems\fR, є такими:
.PP
\fB\-a\fR, \fB\-\-add\fR \fIім\*(Aqя_користувача\fR
.RS 4
Додати користувача до списку участі у групі\&.
.sp
Якщо існує файл
/etc/gshadow, і у групи немає запису у файлі
/etc/gshadow, буде створено новий запис\&.
.RE
.PP
\fB\-d\fR, \fB\-\-delete\fR \fIім\*(Aqя_користувача\fR
.RS 4
Вилучити користувача зі списку участі у групі\&.
.sp
Якщо файл
/etc/gshadow
існує, користувача буде вилучено зі списку учасників і адміністраторів групи\&.
.sp
Якщо існує файл
/etc/gshadow, і у групи немає запису у файлі
/etc/gshadow, буде створено новий запис\&.
.RE
.PP
\fB\-g\fR, \fB\-\-group\fR \fIназва_групи\fR
.RS 4
Надкористувач може вказувати, до якого списку учасників груп слід внести зміни\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показати довідкове повідомлення і завершити роботу\&.
.RE
.PP
\fB\-l\fR, \fB\-\-list\fR
.RS 4
Вивести список участі у групах\&.
.RE
.PP
\fB\-p\fR, \fB\-\-purge\fR
.RS 4
Витерти усіх користувачів зі списку учасників групи\&.
.sp
Якщо існує файл
/etc/gshadow, і у групи немає запису у файлі
/etc/gshadow, буде створено новий запис\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR \fIКАТАЛОГ_CHROOT\fR
.RS 4
Apply changes in the
\fICHROOT_DIR\fR
directory and use the configuration files from the
\fICHROOT_DIR\fR
directory\&. Only absolute paths are supported\&.
.RE
.SH "КОНФІГУРАЦІЯ"
.PP
Режимом доступу до виконуваного файла
\fBgroupmems\fR
має бути
2710
із власником
\fIroot\fR
і групою
\fIgroups\fR\&. Адміністратор системи може додавати користувачів до групи
\fIgroups\fR, щоб дозволити або заборонити їм користуватися програмою
\fBgroupmems\fR
для керування списком учасників їхньої власної групи\&.
.sp
.if n \{\
.RS 4
.\}
.nf
$ groupadd \-r groups $ chmod 2710 groupmems $ chown root\&.groups groupmems $ groupmems \-g groups \-a gk4
.fi
.if n \{\
.RE
.\}
.SH "НАЛАШТУВАННЯ"
.PP
Вказані нижче змінні налаштувань у
/etc/login\&.defs
змінюють поведінку цього інструмента:
.SH "ФАЙЛИ"
.PP
/etc/group
.RS 4
Відомості щодо груп облікових записів\&.
.RE
.PP
/etc/gshadow
.RS 4
відомості щодо захищених груп облікових записів
.RE
.SH "ДИВ\&. ТАКОЖ"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBgroupadd\fR(8),
\fBgroupdel\fR(8),
\fBuseradd\fR(8),
\fBuserdel\fR(8),
\fBusermod\fR(8)\&.
