'\" t
.\"     Title: grpck
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/11/2022
.\"    Manual: Команди керування системою
.\"    Source: shadow-utils 4.13
.\"  Language: Ukrainian
.\"
.TH "grpck" "8" "08/11/2022" "shadow\-utils 4\&.13" "Команди керування системою"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
grpck \- перевірка цілісності файлів груп
.SH "КОРОТКИЙ ОГЛЯД"
.HP \w'\fBgrpck\fR\ 'u
\fBgrpck\fR [параметри] [\fIгрупа\fR\ [\ \fIshadow\fR\ ]]
.SH "ОПИС"
.PP
Команду
\fBgrpck\fR
призначено для перевірки цілісності даних щодо груп\&. Вона перевіряє, чи усі записи у
/etc/group
and /etc/gshadow
мають належне форматування і містять чинні дані\&. Програма попросить користувача вилучити записи із помилковим форматуванням або іншими непридатними до виправлення помилками\&.
.PP
Буде виконано перевірки з метою переконатися, що кожен запис має:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
належна кількість полів
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
унікальна і чинна назва групи
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
чинний ідентифікатор групи
(/etc/group only)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
коректний список учасників
і адміністратори
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
відповідний запис у файлі
/etc/gshadow
(відповідно,
/etc/group
для перевірок
gshadow)
.RE
.PP
Перевірки належної кількості полів та унікальності назв груп є критичними\&. Якщо у записі помилкова кількість полів, програма попросить користувача вилучити увесь рядок\&. Якщо користувач не підтвердить дію з вилучення, усі наступні перевірки буде пропущено\&. Якщо буде виявлено запис із дублюванням групи, програма попросить вилучити його, але якщо у цьому буде відмовлено, виконає решту перевірок\&. Усі інші помилки вважатимуться незначними \(em користувачу буде рекомендовано віддати команду
\fBgroupmod\fR, щоб виправити помилку\&.
.PP
Команди, які мають справу з
/etc/group
and /etc/gshadow files, не зможуть змінити пошкоджені або дубльовані записи\&. У цих випадках слід скористатися
\fBgrpck\fR
для вилучення помилкових записів\&.
.SH "ПАРАМЕТРИ"
.PP
Параметри
\fB\-r\fR
і
\fB\-s\fR
не можна поєднувати\&.
.PP
Параметри, які застосовують до команди
\fBgrpck\fR, є такими:
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показати довідкове повідомлення і завершити роботу\&.
.RE
.PP
\fB\-r\fR, \fB\-\-read\-only\fR
.RS 4
Виконати команду
\fBgrpck\fR
у режимі лише читання\&. Це призведе до того, що програма вважатиме відповідями на усі свої питання значення
\fIno\fR
і ні про що не запитуватиме користувача\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR \fIКАТАЛОГ_CHROOT\fR
.RS 4
Apply changes in the
\fICHROOT_DIR\fR
directory and use the configuration files from the
\fICHROOT_DIR\fR
directory\&. Only absolute paths are supported\&.
.RE
.PP
\fB\-s\fR, \fB\-\-sort\fR
.RS 4
Упорядкувати записи у
/etc/group
and /etc/gshadow
за GID\&.
.RE
.PP
\fB\-S\fR, \fB\-\-silence\-warnings\fR
.RS 4
Придушити сумнівні попередження, зокрема попередження щодо неузгодженості між списками учасників групи у
/etc/group
і
/etc/ghadow\&.
.RE
.PP
Типово,
\fBgrpck\fR
працює з
/etc/group
and /etc/gshadow\&. Користувач може вибрати альтернативні файли за допомогою
\fIгрупа\fR
and \fIshadow\fR parameters\&.
.SH "НАЛАШТУВАННЯ"
.PP
Вказані нижче змінні налаштувань у
/etc/login\&.defs
змінюють поведінку цього інструмента:
.SH "ФАЙЛИ"
.PP
/etc/group
.RS 4
Відомості щодо груп облікових записів\&.
.RE
.PP
/etc/gshadow
.RS 4
Відомості щодо захищених груп облікових записів\&.
.RE
.PP
/etc/passwd
.RS 4
Відомості щодо облікових записів користувача\&.
.RE
.SH "ЗНАЧЕННЯ ВИХОДУ"
.PP
Команда
\fBgrpck\fR
завершує роботу із такими значеннями:
.PP
\fI0\fR
.RS 4
успіх
.RE
.PP
\fI1\fR
.RS 4
некоректний синтаксис команди
.RE
.PP
\fI2\fR
.RS 4
один або декілька помилкових записів груп
.RE
.PP
\fI3\fR
.RS 4
не вдалося відкрити файли груп
.RE
.PP
\fI4\fR
.RS 4
не вдалося заблокувати файли груп
.RE
.PP
\fI5\fR
.RS 4
не вдалося оновити файли груп
.RE
.SH "ДИВ\&. ТАКОЖ"
.PP
\fBгрупа\fR(5),
\fBgroupmod\fR(8),
\fBgshadow\fR(5),
\fBpasswd\fR(5),
\fBpwck\fR(8),
\fBshadow\fR(5)\&.
