'\" t
.\"     Title: lastlog
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/11/2022
.\"    Manual: Команди керування системою
.\"    Source: shadow-utils 4.13
.\"  Language: Ukrainian
.\"
.TH "lastlog" "8" "08/11/2022" "shadow\-utils 4\&.13" "Команди керування системою"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
lastlog \- виведення даних щодо останнього входу до системи для усіх користувачів або для вказаного користувача\&.
.SH "КОРОТКИЙ ОГЛЯД"
.HP \w'\fBlastlog\fR\ 'u
\fBlastlog\fR [\fIпараметри\fR]
.SH "ОПИС"
.PP
\fBlastlog\fR
форматує і виводить вміст журналу записів останнього входу до системи у файлі
/var/log/lastlog\&. Буде виведено дані
\fIім\*(Aqя користувача\fR,
\fIпорт\fR
і
\fIчас останнього входу до системи\fR\&. Типовий варіант (без прапорців) призведе до виведення записів lastlog, які буде упорядковано за порядком у
/etc/passwd\&.
.SH "ПАРАМЕТРИ"
.PP
Параметри, які застосовують до команди
\fBlastlog\fR, є такими:
.PP
\fB\-b\fR, \fB\-\-before\fR \fIДНІ\fR
.RS 4
Вивести лише ті записи lastlog, вік яких перевищує
\fIДНІ\fR\&.
.RE
.PP
\fB\-C\fR, \fB\-\-clear\fR
.RS 4
Вилучити запис lastlog користувача\&. Цей параметр можна використовувати лише разом із
\fB\-u\fR
(\fB\-\-user\fR))\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показати довідкове повідомлення і завершити роботу\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR \fIКАТАЛОГ_CHROOT\fR
.RS 4
Apply changes in the
\fICHROOT_DIR\fR
directory and use the configuration files from the
\fICHROOT_DIR\fR
directory\&. Only absolute paths are supported\&.
.RE
.PP
\fB\-S\fR, \fB\-\-set\fR
.RS 4
Встановити для запису lastlog користувача поточний час\&. Цей параметр можна використовувати лише разом із
\fB\-u\fR
(\fB\-\-user\fR))\&.
.RE
.PP
\fB\-t\fR, \fB\-\-time\fR \fIДНІ\fR
.RS 4
Вивести записи lastlog, які є свіжішими за
\fIДНІ\fR\&.
.RE
.PP
\fB\-u\fR, \fB\-\-user\fR \fIЗАПИС\fR|\fIДІАПАЗОН\fR
.RS 4
Вивести запис lastlog для вказаних користувачів\&.
.sp
Користувачів можна задавати за обліковим записом для входу, числовим ідентифікатором користувача або значенням
\fIДІАПАЗОН\fR
для користувачів\&.
\fIДІАПАЗОН\fR
користувачів можна вказати за допомогою мінімального і максимального значень (\fIUID_MIN\-UID_MAX\fR), максимального значення (\fI\-UID_MAX\fR) або мінімального значення (\fIUID_MIN\-\fR)\&.
.RE
.PP
Якщо користувач ніколи не входив до системи, буде виведено повідомлення
\fI** Ніколи не входив **\fR
замість порту і часу\&.
.PP
Буде виведено записи лише для поточних користувачів системи\&. У системі можуть існувати дані для записів користувачів, які було раніше вилучено\&.
.SH "ЗАУВАЖЕННЯ"
.PP
Файл
lastlog
є базою даних, які містить дані щодо останнього входу до системи кожного з користувачів\&. Вам не слід оновлювати його вміст вручну\&. Це розріджений файл, тому його розмір на диску, зазвичай, є набагато меншим за показаний
\fBls \-l\fR
(ця команда може показати дуже великий розмір, якщо у вашому
passwd
є записи із великими значеннями UID)\&. Переглянути справжній розмір файла можна за допомогою команди
\fBls \-s\fR\&.
.SH "НАЛАШТУВАННЯ"
.PP
Вказані нижче змінні налаштувань у
/etc/login\&.defs
змінюють поведінку цього інструмента:
.SH "ФАЙЛИ"
.PP
/var/log/lastlog
.RS 4
Записи часу у базі даних для попередніх входів користувача\&.
.RE
.SH "ЗАСТЕРЕЖЕННЯ"
.PP
Великі прогалини у числах UID призведуть до того, що програма lastlog працюватиме довше без виведення даних на екран (тобто, якщо у базі даних lastlog немає записів для користувачів із UID між 170 і 800, може здатися, що lastlog зависла, доки програма обробляє UID у діапазоні 171\-799)\&.
.PP
Наявність великих значень UID може створити проблеми при обробці
<term>/var/log/lastlog</term>
за допомогою зовнішніх інструментів\&. Хоча сам файл є розрідженим і він не використовує надто багато місця на диску, деякі програми типово не призначено для визначення розріджених файлів \(em такі програми можуть потребувати для обробки певного параметра\&.
