'\" t
.\"     Title: logoutd
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/11/2022
.\"    Manual: Команди керування системою
.\"    Source: shadow-utils 4.13
.\"  Language: Ukrainian
.\"
.TH "logoutd" "8" "08/11/2022" "shadow\-utils 4\&.13" "Команди керування системою"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
logoutd \- примусово застосувати обмеження щодо часу входу
.SH "КОРОТКИЙ ОГЛЯД"
.HP \w'\fBlogoutd\fR\ 'u
\fBlogoutd\fR
.SH "ОПИС"
.PP
\fBlogoutd\fR
накладає обмеження на час входу та порт, які вказано у
/etc/porttime\&.
\fBlogoutd\fR
має бути запущено з
/etc/rc\&. Система виконуватиме регулярне сканування
/var/run/utmp\&. Буде виконано перевірку кожного користувача з метою визначення того, чи має доступ користувач до іменованого порту у поточний момент часу\&. Усі сеанси роботи, які порушуватимуть обмеження у
/etc/porttime, буде перервано\&.
.SH "ФАЙЛИ"
.PP
/etc/porttime
.RS 4
Файл, у якому містяться дані доступу до портів\&.
.RE
.PP
/var/run/utmp
.RS 4
Список поточних сеансів входу до системи\&.
.RE
