'\" t
.\"     Title: newusers
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/11/2022
.\"    Manual: Команди керування системою
.\"    Source: shadow-utils 4.13
.\"  Language: Ukrainian
.\"
.TH "newusers" "8" "08/11/2022" "shadow\-utils 4\&.13" "Команди керування системою"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
newusers \- пакетне оновлення і створення облікових записів користувачів
.SH "КОРОТКИЙ ОГЛЯД"
.HP \w'\fBnewusers\fR\ 'u
\fBnewusers\fR [\fIпараметри\fR] [\fIфайл\fR]
.SH "ОПИС"
.PP
Команда
\fBnewusers\fR
читає
\fIфайл\fR
(або, типово, стандартного джерела вхідних даних) і використовує ці дані для оновлення набору наявних записів користувачів або створення записів нових користувачів\&. Кожен рядок записано у тому самому форматі, що і стандартний файл паролів (див\&.
\fBpasswd\fR(5))\&. Винятки з цього правила описано нижче:
.PP
pw_name:pw_passwd:pw_uid:pw_gid:pw_gecos:pw_dir:pw_shell
.PP
\fIpw_name\fR
.RS 4
Це ім\*(Aqя користувача\&.
.sp
Це може бути ім\*(Aqя нового користувача або ім\*(Aqя наявного користувача (або користувача, запис якого створено раніше за допомогою
\fBnewusers\fR)\&. У випадку наявного користувача буде змінено дані щодо користувача\&. Якщо запису користувача не існуватиме, його буде створено\&.
.RE
.PP
\fIpw_passwd\fR
.RS 4
Це поле буде зашифровано і використано як нове значення зашифрованого пароля\&.
.RE
.PP
\fIpw_uid\fR
.RS 4
Це поле буде використано для визначення UID користувача\&.
.sp
Якщо поле є порожнім, новий (невикористаний) UID буде визначено
\fBnewusers\fR
автоматично\&.
.sp
Якщо у цьому полі міститься число, це число буде використано як UID\&.
.sp
Якщо у цьому полі міститься ім\*(Aqя наявного користувача (або ім\*(Aqя користувача, запис якого було створено раніше за допомогою
\fBnewusers\fR), буде використано UID вказаного користувача\&.
.sp
Якщо буде змінено UID наявного користувача, власність на файли файла користувача має бути виправлено вручну\&.
.RE
.PP
\fIpw_gid\fR
.RS 4
Це поле використовують для визначення ідентифікатора основної групи користувача\&.
.sp
Якщо у цьому полі міститься ім\*(Aqя наявної групи (або групи, яку раніше створено за допомогою
\fBnewusers\fR), GID цієї групи буде використано як ідентифікатор основної групи користувача\&.
.sp
Якщо у цьому полі записано число, це число буде використано як ідентифікатор основної групи користувача\&. Якщо груп із цим GID не існує, буде створено нову групу з цим GID і назвою, яка збігається із іменем користувача\&.
.sp
Якщо це поле є порожнім, буде створено нову групу із назвою, яка збігається із іменем користувача, а GID буде автоматично визначено за допомогою
\fBnewusers\fR
для використання як ідентифікатора основної групи для користувача і як GID для нової групи\&.
.sp
Якщо у цьому полі міститься назва групи, якої не існує (і її не було створено раніше за допомогою
\fBnewusers\fR), буде створено нову групу із вказаною назвою, а GID буде автоматично визначено за допомогою
\fBnewusers\fR
для використання як ідентифікатора основної групи для користувача і GID для нової групи\&.
.RE
.PP
\fIpw_gecos\fR
.RS 4
Це поле буде скопійовано до поля GECOS користувача\&.
.RE
.PP
\fIpw_dir\fR
.RS 4
Це поле призначено для визначення домашнього каталогу користувача\&.
.sp
Якщо це поле не вказує на наявний каталог, вказаний каталог буде створено\&. Власником буде користувач, обліковий запис якого буде створено або оновлено, та його основна група\&. Зауважте, що
\fInewusers не створює батьківських каталогів\fR
домашнього каталогу нового користувача\&. Команда newusers не зможе створити домашній каталог, якщо не існує батьківських щодо нього каталогів, і надішле повідомлення до stderr із інформуванням користувача про помилку\&. Команда newusers не перерве роботу і не поверне помилку до оболонки, з якої її віддано, якщо їй не вдасться створити домашній каталог, а продовжить обробку пакета вказаних нових користувачів\&.
.sp
Якщо буде змінено домашній каталог наявного користувача,
\fBnewusers\fR
не пересуватиме і не копіюватиме вміст старого каталогу до нового місця\&. Це доведеться зробити вручну\&.
.RE
.PP
\fIpw_shell\fR
.RS 4
Це поле визначає командну оболонку користувача\&. Перевірки щодо вмісту цього поля не виконуються\&.
.RE
.PP
\fBnewusers\fR
спочатку намагається створити або змінити дані усіх вказаних користувачів, а потім записує ці зміни до баз даних користувачів або груп\&. Якщо станеться помилка (окрім остаточного запису до баз даних), змін до баз даних не вноситимуться\&.
.PP
Цю команду призначено для використання у великих системних середовищах, де одночасно оновлюють багато облікових записів\&.
.SH "ПАРАМЕТРИ"
.PP
Параметри, які застосовують до команди
\fBnewusers\fR, є такими:
.PP
\fB\-\-badname\fR\ \&
.RS 4
Дозволити назви, які не відповідають стандартам\&.
.RE
.PP
\fB\-c\fR, \fB\-\-crypt\-method\fR
.RS 4
Скористатися для шифрування паролів вказаним методом\&.
.sp
Доступними методами є DES, MD5, NONE і SHA256 або SHA512, якщо у вашій libc передбачено підтримку цих методів\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показати довідкове повідомлення і завершити роботу\&.
.RE
.PP
\fB\-r\fR, \fB\-\-system\fR
.RS 4
Створити загальносистемний обліковий запис\&.
.sp
Записи загальносистемних користувачів буде створено без даних щодо застарівання у
/etc/shadow, а їхні числові ідентифікатори буде вибрано у діапазоні
\fBSYS_UID_MIN\fR\-\fBSYS_UID_MAX\fR, який визначено у
login\&.defs, а не у
\fBUID_MIN\fR\-\fBUID_MAX\fR
(та їхніх відповідників
\fBGID\fR
для створення груп)\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR \fIКАТАЛОГ_CHROOT\fR
.RS 4
Apply changes in the
\fICHROOT_DIR\fR
directory and use the configuration files from the
\fICHROOT_DIR\fR
directory\&. Only absolute paths are supported\&.
.RE
.PP
\fB\-s\fR, \fB\-\-sha\-rounds\fR
.RS 4
Використати вказану кількість циклів шифрування паролів\&.
.sp
Значення 0 означає, що система вибере типову кількість проходів для методу шифрування (5000)\&.
.sp
Буде примусово встановлено мінімальне значення 1000 і максимальне значення 999999999\&.
.sp
Ви можете скористатися цим параметром у поєднанні із методами шифрування SHA256 або SHA512\&.
.sp
Типово, кількість проходів визначається за допомогою змінних SHA_CRYPT_MIN_ROUNDS і SHA_CRYPT_MAX_ROUNDS у
/etc/login\&.defs\&.
.RE
.SH "ЗАСТЕРЕЖЕННЯ"
.PP
Файл вхідних даних має бути захищено, оскільки у ньому зберігаються незашифровані паролі\&.
.PP
Вам слід переконатися, що паролі і метод шифрування відповідає правилам поводження з паролями у системі\&.
.SH "НАЛАШТУВАННЯ"
.PP
Вказані нижче змінні налаштувань у
/etc/login\&.defs
змінюють поведінку цього інструмента:





.SH "ФАЙЛИ"
.PP
/etc/passwd
.RS 4
Відомості щодо облікових записів користувача\&.
.RE
.PP
/etc/shadow
.RS 4
Відомості щодо захищених облікових записів користувачів\&.
.RE
.PP
/etc/group
.RS 4
Відомості щодо груп облікових записів\&.
.RE
.PP
/etc/gshadow
.RS 4
Відомості щодо захищених груп облікових записів\&.
.RE
.PP
/etc/login\&.defs
.RS 4
Налаштування комплексу для роботи з прихованими паролями\&.
.RE
.PP
/etc/subgid
.RS 4
Окремі для користувачів ідентифікатори підлеглих груп\&.
.RE
.PP
/etc/subuid
.RS 4
Окремі для користувачів ідентифікатори підлеглих користувачів\&.
.RE
.SH "ДИВ\&. ТАКОЖ"
.PP
\fBlogin.defs\fR(5),
\fBpasswd\fR(1),
\fBsubgid\fR(5), \fBsubuid\fR(5),
\fBuseradd\fR(8)\&.
