'\" t
.\"     Title: nologin
.\"    Author: Nicolas Fran\(,cois <nicolas.francois@centraliens.net>
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/11/2022
.\"    Manual: Команди керування системою
.\"    Source: shadow-utils 4.13
.\"  Language: Ukrainian
.\"
.TH "nologin" "8" "08/11/2022" "shadow\-utils 4\&.13" "Команди керування системою"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
nologin \- увічливо відмовити у вході до системи
.SH "КОРОТКИЙ ОГЛЯД"
.HP \w'\fBnologin\fR\ 'u
\fBnologin\fR
.SH "ОПИС"
.PP
Команда
\fBnologin\fR
виводить повідомлення про те, що обліковий запис є недоступним, і завершує роботу із ненульовим станом\&. Команду призначено на заміну поля командної оболонки для облікових записів, які було вимкнено\&.
.PP
Щоб взагалі вимкнути можливість входу, ознайомтеся із документацією до
\fBnologin\fR(5)\&.
.PP
Якщо встановлено значення
\fBSSH_ORIGINAL_COMMAND\fR, дані буде записано до журналу\&.
.SH "ДИВ\&. ТАКОЖ"
.PP
\fBlogin\fR(1),
\fBnologin\fR(5)\&.
.SH "ІСТОРІЯ"
.PP
Команда
\fBnologin\fR
з\*(Aqявилася у BSD 4\&.4\&.
