'\" t
.\"     Title: pwck
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/11/2022
.\"    Manual: Команди керування системою
.\"    Source: shadow-utils 4.13
.\"  Language: Ukrainian
.\"
.TH "pwck" "8" "08/11/2022" "shadow\-utils 4\&.13" "Команди керування системою"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
pwck \- перевірка цілісності файлів паролів
.SH "КОРОТКИЙ ОГЛЯД"
.HP \w'\fBpwck\fR\ 'u
\fBpwck\fR [параметри] [\fIФАЙЛ_ПАРОЛІВ\fR\ [\ \fIФАЙЛ_SHADOW\fR\ ]]
.SH "ОПИС"
.PP
Команду
\fBpwck\fR
призначено для перевірки цілісності даних щодо користувачів і розпізнавання\&. Вона перевіряє, чи усі записи у
/etc/passwd
і
/etc/shadowмають належне форматування і містять чинні дані\&. Програма попросить користувача вилучити записи із помилковим форматуванням або іншими непридатними до виправлення помилками\&.
.PP
Буде виконано перевірки з метою переконатися, що кожен запис має:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
належна кількість полів
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
унікальне і чинне ім\*(Aqя користувача
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
чинний ідентифікатор користувача і групи
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
чинна основна група
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
чинний домашній каталог
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
чинна оболонка входу
.RE
.PP
Перевірки для даних прихованих паролів буде увімкнено, якщо вказано другий параметр файла
\fIФАЙЛ_SHADOW\fR
або якщо у системі існує
/etc/shadow\&.
.PP
Цими перевірками є такі:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
У кожного запису passwd є відповідний запис shadow, а кожен запис shadow має відповідний запис passwd
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Паролі вказано у файлі прихованих паролів
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Записи shadow мають належну кількість полів
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Записи shadow є унікальними у shadow
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
останні зміни паролів не позначено часовими позначками у майбутньому
.RE
.PP
Перевірки належної кількості полів та унікальності імен користувачів є критичними\&. Якщо у записі помилкова кількість полів, програма попросить користувача вилучити увесь рядок\&. Якщо користувач не підтвердить дію з вилучення, усі наступні перевірки буде пропущено\&. Якщо буде виявлено запис із дублюванням імені користувача, програма попросить вилучити його, але якщо у цьому буде відмовлено, виконає решту перевірок\&. Усі інші помилки вважатимуться незначними \(em користувачу буде рекомендовано віддати команду
\fBusermod\fR, щоб виправити помилку\&.
.PP
Команди, які мають справу з файлом
/etc/passwd, не зможуть змінити пошкоджені або дубльовані записи\&. У цих випадках слід скористатися
\fBpwck\fR
для вилучення помилкового запису\&.
.SH "ПАРАМЕТРИ"
.PP
Параметри
\fB\-r\fR
і
\fB\-s\fR
не можна поєднувати\&.
.PP
Параметри, які застосовують до команди
\fBpwck\fR, є такими:
.PP
\fB\-\-badname\fR\ \&
.RS 4
Дозволити назви, які не відповідають стандартам\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показати довідкове повідомлення і завершити роботу\&.
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
Повідомляти лише про помилки\&. Попередження, які не потребують взаємодії із користувачем, виведено не буде\&.
.RE
.PP
\fB\-r\fR, \fB\-\-read\-only\fR
.RS 4
Виконати команду
\fBpwck\fR
у режимі лише читання\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR \fIКАТАЛОГ_CHROOT\fR
.RS 4
Apply changes in the
\fICHROOT_DIR\fR
directory and use the configuration files from the
\fICHROOT_DIR\fR
directory\&. Only absolute paths are supported\&.
.RE
.PP
\fB\-s\fR, \fB\-\-sort\fR
.RS 4
Упорядкувати записи у
/etc/passwd
і
/etc/shadow
за UID\&.
.RE
.PP
Типово,
\fBpwck\fR
працює з файлами
/etc/passwd
і
/etc/shadow\&. Користувач може вибрати альтернативні файли за допомогою параметрів
\fIpasswd\fR
і
\fIshadow\fR\&.
.SH "НАЛАШТУВАННЯ"
.PP
Вказані нижче змінні налаштувань у
/etc/login\&.defs
змінюють поведінку цього інструмента:
.SH "ФАЙЛИ"
.PP
/etc/group
.RS 4
Відомості щодо груп облікових записів\&.
.RE
.PP
/etc/passwd
.RS 4
Відомості щодо облікових записів користувача\&.
.RE
.PP
/etc/shadow
.RS 4
Відомості щодо захищених облікових записів користувачів\&.
.RE
.SH "ЗНАЧЕННЯ ВИХОДУ"
.PP
Команда
\fBpwck\fR
завершує роботу із такими значеннями:
.PP
\fI0\fR
.RS 4
успіх
.RE
.PP
\fI1\fR
.RS 4
некоректний синтаксис команди
.RE
.PP
\fI2\fR
.RS 4
одна або декілька невдалих спроб ввести пароль
.RE
.PP
\fI3\fR
.RS 4
не вдалося відкрити файли паролів
.RE
.PP
\fI4\fR
.RS 4
не вдалося заблокувати файли паролів
.RE
.PP
\fI5\fR
.RS 4
не вдалося оновити файли паролів
.RE
.PP
\fI6\fR
.RS 4
не вдалося упорядкувати файли паролів
.RE
.SH "ДИВ\&. ТАКОЖ"
.PP
\fBгрупа\fR(5),
\fBgrpck\fR(8),
\fBpasswd\fR(5),
\fBshadow\fR(5),
\fBusermod\fR(8)\&.
