'\" t
.\"     Title: usermod
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/11/2022
.\"    Manual: Команди керування системою
.\"    Source: shadow-utils 4.13
.\"  Language: Ukrainian
.\"
.TH "usermod" "8" "08/11/2022" "shadow\-utils 4\&.13" "Команди керування системою"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
usermod \- зміна облікового запису користувача
.SH "КОРОТКИЙ ОГЛЯД"
.HP \w'\fBusermod\fR\ 'u
\fBusermod\fR [\fIпараметри\fR] \fIЗАПИС\fR
.SH "ОПИС"
.PP
\fBusermod\fR
вносить зміни до файлів загальносистемних облікових записів\&.
.SH "ПАРАМЕТРИ"
.PP
Параметри, які застосовують до команди
\fBusermod\fR, є такими:
.PP
\fB\-a\fR, \fB\-\-append\fR
.RS 4
Додати користувача до допоміжних груп\&. Використовуйте лише у поєднанні з параметром
\fB\-G\fR\&.
.RE
.PP
\fB\-b\fR, \fB\-\-badname\fR
.RS 4
Дозволити назви, які не відповідають стандартам\&.
.RE
.PP
\fB\-c\fR, \fB\-\-comment\fR \fIКОМЕНТАР\fR
.RS 4
Оновити поле коментаря для запису користувача у
/etc/passwd, зміни до якого, зазвичай, вносять за допомогою допоміжного засобу
\fBchfn\fR(1)\&.
.RE
.PP
\fB\-d\fR, \fB\-\-home\fR \fIДОМАШНІЙ_КАТАЛОГ\fR
.RS 4
Новий каталог користувача для облікового запису входу до системи\&.
.sp
Якщо вказано параметр
\fB\-m\fR, вміст поточного домашнього каталогу буде пересунуто до нового домашнього каталогу, який буде створено, якщо його ще не існує\&. Якщо поточного домашнього каталогу не існує, новий домашній каталог створено не буде\&.
.RE
.PP
\fB\-e\fR, \fB\-\-expiredate\fR \fIДАТА_ЗАВЕРШЕННЯ_СТРОКУ_ДІЇ\fR
.RS 4
Дата, у яку буде вимкнено обліковий запис користувача\&. Дату вказують у форматі
\fIРРРР\-ММ\-ДД\fR\&. Цілі вхідні числа буде оброблено як дні після 1 січня 1970 року\&.
.sp
Вхідне значення \-1 або порожній рядок призведуть до вилучення вмісту поля строку дії облікового запису у файлі паролів shadow\&. Обліковий запис лишиться доступним, але без обмеження за датами\&.
.sp
Цей параметр потребує файла
/etc/shadow\&. Запис
/etc/shadow
буде створено, якщо такого ще немає\&.
.RE
.PP
\fB\-f\fR, \fB\-\-inactive\fR \fIНЕАКТИВНИЙ\fR
.RS 4
Визначає період у кількості днів після перевищення максимального віку, протягом якого користувач усе ще матиме змогу увійти до системи з негайною зміною пароля\&. Цей період лояльності до того, як обліковий запис стане неактивним, зберігається у файлі прихованих паролів (shadow)\&. Вхідне значення 0 означає негайне вимикання пароля, строк дії якого вичерпано\&. Вхідне значення \-1 призведе до вилучення вмісту відповідного поля у файлі прихованих паролів (shadow)\&. Див\&.
\fBshadow\fR(5), щоб дізнатися більше\&.
.sp
Цей параметр потребує файла
/etc/shadow\&. Запис
/etc/shadow
буде створено, якщо такого ще немає\&.
.RE
.PP
\fB\-g\fR, \fB\-\-gid\fR \fIGROUP\fR
.RS 4
Назва або числовий ідентифікатор нової основної групи користувача\&. Група має існувати\&.
.sp
Власником будь\-якого файла з домашнього каталогу користувача, власником якого була попередня основна група користувача, буде ця нова група\&.
.sp
Права власності на файли поза домашнім каталогом користувача має бути виправлено вручну\&.
.sp
Зміну групи\-власника для файлів у домашньому каталозі користувача також не буде виконано, якщо uid власника домашнього каталогу відрізняється від ідентифікатора поточного або нового користувача\&. Це захід безпеки для особливих домашніх каталогів, зокрема
/\&.
.RE
.PP
\fB\-G\fR, \fB\-\-groups\fR \fIГРУПА1\fR[\fI,ГРУПА2,\&.\&.\&.\fR[\fI,ГРУПАN\fR]]]
.RS 4
Список допоміжних груп, учасником яких є користувач\&. Записи у списку слід відокремлювати комами, без проміжного пробілу\&. Групи мають існувати\&.
.sp
Якщо користувач у поточний момент є учасником групи, якої немає у списку, його запис буде вилучено з цієї групи\&. Змінити цю поведінку можна за допомогою параметра
\fB\-a\fR, який дописує запис користувача до поточного списку допоміжних груп\&.
.RE
.PP
\fB\-l\fR, \fB\-\-login\fR \fIНОВИЙ_ЗАПИС\fR
.RS 4
Ім\*(Aqя користувача буде змінено з
\fIЗАПИС\fR
на
\fIНОВИЙ_ЗАПИС\fR\&. Нічого, окрім цього, змінено не буде\&. Зокрема, ймовірно, назву домашнього каталогу користувача та поштового буфера доведеться змінювати вручну, щоб синхронізувати їх із новою назвою облікового запису для входу до системи\&.
.RE
.PP
\fB\-L\fR, \fB\-\-lock\fR
.RS 4
Заблокувати пароль користувача\&. У відповідь на команду програма допише \(Fo!\(Fc перед зашифрованим паролем, фактично, вимкнувши пароль\&. Цей параметр не можна поєднувати з
\fB\-p\fR
та
\fB\-U\fR\&.
.sp
Зауваження: якщо ви хочете заблокувати обліковий запис (а не лише доступ за допомогою пароля), вам також слід встановити для
\fIДАТА_ЗАВЕРШЕННЯ_СТРОКУ_ДІЇ\fR
значення
\fI1\fR\&.
.RE
.PP
\fB\-m\fR, \fB\-\-move\-home\fR
.RS 4
Пересуває вміст домашнього каталогу користувача у нове місце\&. Якщо поточного домашнього каталогу не існує, буде створено новий домашній каталог\&.
.sp
Цей параметр є чинним, лише у поєднанні із параметром
\fB\-d\fR
(або
\fB\-\-home\fR)\&.
.sp
\fBusermod\fR
спробує адаптувати права власності на файли і скопіювати режими доступу, ACL та розширені атрибути, але згодом може знадобитися внесення змін вручну\&.
.RE
.PP
\fB\-o\fR, \fB\-\-non\-unique\fR
.RS 4
Дозволяє зміну ідентифікатора користувача на неунікальне значення\&.
.sp
Цей параметр можна використовувати лише у поєднанні із параметром
\fB\-u\fR\&. Оскільки профіль користувача слугує ключем для прив\*(Aqязки користувачів до прав доступу, прав власності на файли та інших аспектів загальносистемної поведінки, доступ до облікового запису із заданим UID матимуть декілька облікових записів для входу до системи\&.
.RE
.PP
\fB\-p\fR, \fB\-\-password\fR \fIПАРОЛЬ\fR
.RS 4
Визначає новий пароль до облікового запису користувача\&. ПАРОЛЬ має бути зашифровано у форматі, який повертає
\fBcrypt\fR(3)\&.
.sp
\fBЗауваження:\fR
не рекомендуємо користуватися цим параметром у командному рядку, оскільки пароль (або шифрований пароль) буде видимим для користувачів, які мають доступ до списку процесів\&.
.sp
Вам слід переконатися, що пароль відповідає правилам складання паролів системи\&.
.RE
.PP
\fB\-r\fR, \fB\-\-remove\fR
.RS 4
Вилучити користувача з іменованих допоміжних груп\&. Використовуйте лише у поєднанні з параметром
\fB\-G\fR\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR \fIКАТАЛОГ_CHROOT\fR
.RS 4
Apply changes in the
\fICHROOT_DIR\fR
directory and use the configuration files from the
\fICHROOT_DIR\fR
directory\&. Only absolute paths are supported\&.
.RE
.PP
\fB\-P\fR, \fB\-\-prefix\fR \fIКАТАЛОГ_ПРЕФІКСА\fR
.RS 4
Застосувати зміни в ієрархії каталогів, що починається з
\fIКАТАЛОГ_ПРЕФІКСА\fR
і використати також файли налаштувань, які там зберігаються\&. Використання цього параметра не змінює кореневої теки\&. Параметр призначено лише для приготування цілі для компіляції коду для іншої операційної системи\&. Обмеження: не буде виконано перевірку користувачів/груп NIS і LDAP\&. При розпізнаванні у PAM буде використано файли основної системи\&. Підтримки SELINUX не передбачено\&.
.RE
.PP
\fB\-s\fR, \fB\-\-shell\fR \fIОБОЛОНКА\fR
.RS 4
Змінює оболонку для входу до системи користувача\&. Визначення порожнього рядка для ОБОЛОНКИ вилучає вміст поля у
/etc/passwd
і виконає вхід користувача до типової оболонки системи\&.
.RE
.PP
\fB\-u\fR, \fB\-\-uid\fR \fIUID\fR
.RS 4
Нове значення ідентифікатора користувача\&.
.sp
Це значення має бути унікальним, якщо не використано параметр
\fB\-o\fR\&. Значення має бути невід\*(Aqємним\&.
.sp
Ідентифікатори користувача файла поштової скриньки користувача і усіх файлів, власником яких є користувач і які зберігаються у домашньому каталозі користувача, буде змінено автоматично\&.
.sp
Права власності на файли поза домашнім каталогом користувача має бути виправлено вручну\&.
.sp
Зміну користувача\-власника для файлів у домашньому каталозі користувача також не буде виконано, якщо uid власника домашнього каталогу відрізняється від ідентифікатора поточного або нового користувача\&. Це захід безпеки для особливих домашніх каталогів, зокрема
/\&.
.sp
Перевірок щодо
\fBUID_MIN\fR,
\fBUID_MAX\fR,
\fBSYS_UID_MIN\fR
або
\fBSYS_UID_MAX\fR
з
/etc/login\&.defs
виконано не буде\&.
.RE
.PP
\fB\-U\fR, \fB\-\-unlock\fR
.RS 4
Розблокувати пароль користувача\&. У відповідь на команду програма вилучить \(Fo!\(Fc перед зашифрованим паролем\&. Цей параметр не можна поєднувати з
\fB\-p\fR
та
\fB\-L\fR\&.
.sp
Зауваження: якщо ви хочете розблокувати обліковий запис (а не лише доступ за допомогою пароля), вам також слід встановити значення для
\fIДАТА_ЗАВЕРШЕННЯ_СТРОКУ_ДІЇ\fR
(наприклад,
\fI99999\fR
або значення
\fBEXPIRE\fR
з
/etc/default/useradd)\&.
.RE
.PP
\fB\-v\fR, \fB\-\-add\-subuids\fR \fIПЕРШИЙ\fR\-\fIОСТАННІЙ\fR
.RS 4
Додати діапазон підлеглих UID до облікового запису користувача\&.
.sp
Цей параметр можна вказувати декілька разів у одній команді, щоб додати декілька діапазонів до облікового запису користувача\&.
.sp
Перевірок щодо
\fBSUB_UID_MIN\fR,
\fBSUB_UID_MAX\fR
та
\fBSUB_UID_COUNT\fR
з /etc/login\&.defs не виконуватиметься\&.
.RE
.PP
\fB\-V\fR, \fB\-\-del\-subuids\fR \fIПЕРШИЙ\fR\-\fIОСТАННІЙ\fR
.RS 4
Вилучити діапазон підлеглих UID з облікового запису користувача\&.
.sp
Цей параметр можна вказати декілька разів, щоб вилучити декілька діапазонів з облікового запису користувача\&. Якщо вказано одразу
\fB\-\-del\-subuids\fR
і
\fB\-\-add\-subuids\fR, вилучення усіх підлеглих діапазонів UID станеться до додавання будь\-яких підлеглих UID\&.
.sp
Перевірок щодо
\fBSUB_UID_MIN\fR,
\fBSUB_UID_MAX\fR
та
\fBSUB_UID_COUNT\fR
з /etc/login\&.defs не виконуватиметься\&.
.RE
.PP
\fB\-w\fR, \fB\-\-add\-subgids\fR \fIПЕРШИЙ\fR\-\fIОСТАННІЙ\fR
.RS 4
Додати діапазон підлеглих GID до облікового запису користувача\&.
.sp
Цей параметр можна вказувати декілька разів у одній команді, щоб додати декілька діапазонів до облікового запису користувача\&.
.sp
Перевірок щодо
\fBSUB_GID_MIN\fR,
\fBSUB_GID_MAX\fR
та
\fBSUB_GID_COUNT\fR
з /etc/login\&.defs не виконуватиметься\&.
.RE
.PP
\fB\-W\fR, \fB\-\-del\-subgids\fR \fIПЕРШИЙ\fR\-\fIОСТАННІЙ\fR
.RS 4
Вилучити діапазон підлеглих GID з облікового запису користувача\&.
.sp
Цей параметр можна вказати декілька разів, щоб вилучити декілька діапазонів з облікового запису користувача\&. Якщо вказано одразу
\fB\-\-del\-subgids\fR
і
\fB\-\-add\-subgids\fR, вилучення усіх підлеглих діапазонів GID станеться до додавання будь\-яких підлеглих GID\&.
.sp
Перевірок щодо
\fBSUB_GID_MIN\fR,
\fBSUB_GID_MAX\fR
та
\fBSUB_GID_COUNT\fR
з /etc/login\&.defs не виконуватиметься\&.
.RE
.PP
\fB\-Z\fR, \fB\-\-selinux\-user\fR \fISEКОРИСТУВАЧ\fR
.RS 4
Визначає пов\*(Aqязаного користувача SELinux за допомогою
\fIЗАПИС\fR\&. Якщо вказати порожній рядок (""), відповідний запис (якщо такий був) буде вилучено\&. Зауважте, що система shadow не зберігає користувача selinux, а використовує для цього semanage(8)\&.
.RE
.SH "ЗАСТЕРЕЖЕННЯ"
.PP
Вам слід переконатися, що від імені вказаного користувача не виконується жодних процесів на момент віддання цієї команди, якщо вносяться зміни до числового ідентифікатора користувача, імені користувача або домашнього каталогу користувача\&. У Linux перевірку цього виконує
\fBusermod\fR\&. У інших операційних системах програма використовує лише utmp для перевірки того, чи увійшов користувач до системи\&.
.PP
Вам слід змінити власника усіх файлів
\fBcrontab\fR
або завдань
\fBat\fR
вручну\&.
.PP
Вам слід внести усі зміни щодо NIS на сервері NIS\&.
.SH "НАЛАШТУВАННЯ"
.PP
Вказані нижче змінні налаштувань у
/etc/login\&.defs
змінюють поведінку цього інструмента:
.SH "ФАЙЛИ"
.PP
/etc/group
.RS 4
Відомості щодо груп облікових записів
.RE
.PP
/etc/gshadow
.RS 4
Відомості щодо захищених груп облікових записів\&.
.RE
.PP
/etc/login\&.defs
.RS 4
Налаштування комплексу для роботи з прихованими паролями
.RE
.PP
/etc/passwd
.RS 4
Відомості щодо облікових записів користувача
.RE
.PP
/etc/shadow
.RS 4
Відомості щодо захищених облікових записів користувачів
.RE
.PP
/etc/subgid
.RS 4
Окремі для користувачів ідентифікатори підлеглих груп
.RE
.PP
/etc/subuid
.RS 4
Окремі для користувачів ідентифікатори підлеглих користувачів
.RE
.SH "ДИВ\&. ТАКОЖ"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBcrypt\fR(3),
\fBgpasswd\fR(8),
\fBgroupadd\fR(8),
\fBgroupdel\fR(8),
\fBgroupmod\fR(8),
\fBlogin.defs\fR(5),
\fBsubgid\fR(5), \fBsubuid\fR(5),
\fBuseradd\fR(8),
\fBuserdel\fR(8)\&.
