'\" t
.\"     Title: userdel
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/11/2022
.\"    Manual: Команди керування системою
.\"    Source: shadow-utils 4.13
.\"  Language: Ukrainian
.\"
.TH "userdel" "8" "08/11/2022" "shadow\-utils 4\&.13" "Команди керування системою"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
userdel \- вилучення облікового запису користувача і пов\*(Aqязаних файлів
.SH "КОРОТКИЙ ОГЛЯД"
.HP \w'\fBuserdel\fR\ 'u
\fBuserdel\fR [параметри] \fIЗАПИС\fR
.SH "ОПИС"
.PP
Команда
\fBuserdel\fR
вносить зміни до файлів загальносистемних облікових записів, вилучаючи усі записи, які стосуються імені користувача
\fIЗАПИС\fR\&. Іменований запис користувача має існувати\&.
.SH "ПАРАМЕТРИ"
.PP
Параметри, які застосовують до команди
\fBuserdel\fR, є такими:
.PP
\fB\-f\fR, \fB\-\-force\fR
.RS 4
Цей параметр наказує програмі вилучити обліковий запис користувача, навіть якщо користувач усе ще працює у системі\&. Також він наказує
\fBuserdel\fR
вилучити домашній каталог користувача і поштовий буфер, навіть якщо цим домашнім каталогом користується інший користувач або якщо власником поштового буфера не є вказаний користувач\&. Якщо для
\fBUSERGROUPS_ENAB\fR
встановлено значення
\fIтак\fR
у
/etc/login\&.defs, і якщо існує група із тією самою назвою, що і назва облікового запису, цю групу буде вилучено, навіть якщо вона все ще є основною групою іншого користувача\&.
.sp
\fIЗауваження:\fR
цей параметр є небезпечним і може перевести вашу систему у неузгоджений стан\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показати довідкове повідомлення і завершити роботу\&.
.RE
.PP
\fB\-r\fR, \fB\-\-remove\fR
.RS 4
Файли у домашньому каталозі користувача буде вилучено разом з самим домашнім каталогом та поштовим буфером користувача\&. Файли у інших файлових системах слід знайти і вилучити вручну\&.
.sp
Поштовий буфер визначається змінною
\fBMAIL_DIR\fR
у файлі
login\&.defs\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR \fIКАТАЛОГ_CHROOT\fR
.RS 4
Apply changes in the
\fICHROOT_DIR\fR
directory and use the configuration files from the
\fICHROOT_DIR\fR
directory\&. Only absolute paths are supported\&.
.RE
.PP
\fB\-P\fR, \fB\-\-prefix\fR \fIКАТАЛОГ_ПРЕФІКСА\fR
.RS 4
Застосувати зміни до каталогу
\fIКАТАЛОГ_ПРЕФІКСА\fR
і використати файли налаштувань з каталогу
\fIКАТАЛОГ_ПРЕФІКСА\fR\&. Використання цього параметра не змінює кореневої теки\&. Параметр призначено лише для приготування цілі для компіляції коду для іншої операційної системи\&. Обмеження: не буде виконано перевірку користувачів/груп NIS і LDAP\&. При розпізнаванні у PAM буде використано файли основної системи\&. Підтримки SELINUX не передбачено\&.
.RE
.PP
\fB\-Z\fR, \fB\-\-selinux\-user\fR
.RS 4
Вилучити усі прив\*(Aqязки до користувача SELinux для облікового запису користувача для входу до системи\&.
.RE
.SH "НАЛАШТУВАННЯ"
.PP
Вказані нижче змінні налаштувань у
/etc/login\&.defs
змінюють поведінку цього інструмента:
.SH "ФАЙЛИ"
.PP
/etc/group
.RS 4
Відомості щодо груп облікових записів\&.
.RE
.PP
/etc/login\&.defs
.RS 4
Налаштування комплексу для роботи з прихованими паролями\&.
.RE
.PP
/etc/passwd
.RS 4
Відомості щодо облікових записів користувача\&.
.RE
.PP
/etc/shadow
.RS 4
Відомості щодо захищених облікових записів користувачів\&.
.RE
.PP
/etc/shadow\-maint/userdel\-pre\&.d/*, /etc/shadow\-maint/userdel\-post\&.d/*
.RS 4
Файли, які буде виконано під час вилучення запису користувача\&. Змінну середовища
\fBACTION\fR
буде заповнено командами
\fBuserdel\fR
і
\fBSUBJECT\fR
з іменем користувача\&. Перед вилученням запису користувача буде виконано
userdel\-pre\&.d\&. Після додавання запису користувача буде виконано
userdel\-post\&.d\&. Якщо станом виходу зі скрипту буде ненульове значення, виконання дій буде перервано\&.
.RE
.PP
/etc/subgid
.RS 4
Окремі для користувачів ідентифікатори підлеглих груп\&.
.RE
.PP
/etc/subuid
.RS 4
Окремі для користувачів ідентифікатори підлеглих користувачів\&.
.RE
.SH "ЗНАЧЕННЯ ВИХОДУ"
.PP
Команда
\fBuserdel\fR
завершує роботу із такими значеннями:
.PP
\fI0\fR
.RS 4
успіх
.RE
.PP
\fI1\fR
.RS 4
не вдалося оновити файл паролів
.RE
.PP
\fI2\fR
.RS 4
некоректний синтаксис команди
.RE
.PP
\fI6\fR
.RS 4
вказаного запису користувача не існує
.RE
.PP
\fI8\fR
.RS 4
поточний користувач системи
.RE
.PP
\fI10\fR
.RS 4
не вдалося оновити файл груп
.RE
.PP
\fI12\fR
.RS 4
не вдалося вилучити домашній каталог
.RE
.SH "ЗАСТЕРЕЖЕННЯ"
.PP
\fBuserdel\fR
не дозволить вам вилучити обліковий запис, якщо цьому обліковому запису належать якісь запущені процеси\&. У випадку наявності таких процесів ви можете завершити їх роботу або заблокувати пароль чи обліковий запис користувача і вилучити обліковий запис пізніше\&. Виконати вилучення цього облікового запису у примусовому режимі можна за допомогою параметра
\fB\-f\fR\&.
.PP
Вам слід виконати перевірку усіх файлових систем вручну, щоб переконатися, щоб не лишилося жодних файлів, які належать цьому користувачу\&.
.PP
Ви не зможете вилучити атрибути NIS з клієнта NIS\&. Виконати це завдання можна лише на сервері NIS\&.
.PP
Якщо для
\fBUSERGROUPS_ENAB\fR
встановлено значення
\fIтак\fR
у
/etc/login\&.defs,
\fBuserdel\fR
вилучить групу, яка має назву, що збігається із назвою облікового запису користувача\&. Щоб уникнути неузгодженостей у базах даних passwd і груп,
\fBuserdel\fR
виконає перевірку того, чи не використовується ця група як основна група іншого користувача\&. Якщо використовується, програма попередить вас без вилучення групи\&. Примусово вилучити цю групу можна за допомогою параметра
\fB\-f\fR\&.
.SH "ДИВ\&. ТАКОЖ"
.PP
\fBchfn\fR(1),
\fBchsh\fR(1),
\fBpasswd\fR(1),
\fBlogin.defs\fR(5),
\fBgpasswd\fR(8),
\fBgroupadd\fR(8),
\fBgroupdel\fR(8),
\fBgroupmod\fR(8),
\fBsubgid\fR(5), \fBsubuid\fR(5),
\fBuseradd\fR(8),
\fBusermod\fR(8)\&.
