'\" t
.\"     Title: chage
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/11/2022
.\"    Manual: Команди користувача
.\"    Source: shadow-utils 4.13
.\"  Language: Ukrainian
.\"
.TH "chage" "1" "08/11/2022" "shadow\-utils 4\&.13" "Команди користувача"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
chage \- зміна даних щодо завершення строку дії пароля користувача
.SH "КОРОТКИЙ ОГЛЯД"
.HP \w'\fBchage\fR\ 'u
\fBchage\fR [\fIпараметри\fR] \fIЗАПИС\fR
.SH "ОПИС"
.PP
Команда
\fBchage\fR
змінює кількість днів між змінами паролів і дату останньої зміни пароля\&. Ці відомості використовує система для визначення того, коли користувач має змінювати пароль\&.
.SH "ПАРАМЕТРИ"
.PP
Параметри, які застосовують до команди
\fBchage\fR, є такими:
.PP
\fB\-d\fR, \fB\-\-lastday\fR \fIОСТАННІЙ_ДЕНЬ\fR
.RS 4
Встановити кількість днів з 1 січня 1970 року, коли пароль було востаннє змінено\&. Дату може бути також вказано у форматі РРРР\-ММ\-ДД (або форматі, який поширений у вашій країні)\&. Якщо для
\fIОСТАННІЙ_ДЕНЬ\fR
встановлено значення
\fI0\fR, користувачеві доведеться змінити пароль під час наступного входу до системи\&.
.RE
.PP
\fB\-E\fR, \fB\-\-expiredate\fR \fIДАТА_ЗАВЕРШЕННЯ_СТРОКУ_ДІЇ\fR
.RS 4
Встановити дату або кількість днів з 1 січня 1970 року, коли слід заборонити доступ до облікового запису користувача\&. Дату може бути також вказано у форматі РРРР\-ММ\-ДД (або форматі, який поширений у вашій країні)\&. Користувач, чий обліковий запис заблоковано, має звернутися до адміністратора системи, перш ніж знову зможе користуватися системою\&.
.sp
Наприклад, наступною командою можна скористатися для встановлення строку дії облікового запису у 180 днів:
.sp
.if n \{\
.RS 4
.\}
.nf
chage \-E $(date \-d +180days +%Y\-%m\-%d)
.fi
.if n \{\
.RE
.\}
.sp
Передавання числа
\fI\-1\fR
у полі
\fIДАТА_ЗАВЕРШЕННЯ_СТРОКУ_ДІЇ\fR
призведе до вилучення дати завершення строку дії облікового запису\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показати довідкове повідомлення і завершити роботу\&.
.RE
.PP
\fB\-i\fR, \fB\-\-iso8601\fR
.RS 4
При виведенні дат користуватися форматом РРРР\-ММ\-ДД\&.
.RE
.PP
\fB\-I\fR, \fB\-\-inactive\fR \fIНЕАКТИВНИЙ\fR
.RS 4
Встановити кількість днів неактивності після завершення строку дії пароля, перш ніж обліковий запис буде заблоковано\&. Значенням параметра
\fIНЕАКТИВНИЙ\fR
має бути кількість днів неактивності\&. Користувач, чий обліковий запис заблоковано, має звернутися до адміністратора системи, перш ніж знову зможе користуватися системою\&.
.sp
Передавання числа
\fI\-1\fR
у полі
\fIНЕАКТИВНИЙ\fR
призведе до вилучення неактивності облікового запису\&.
.RE
.PP
\fB\-l\fR, \fB\-\-list\fR
.RS 4
Показати відомості щодо застарівання облікового запису\&.
.RE
.PP
\fB\-m\fR, \fB\-\-mindays\fR \fIДНІ\fR
.RS 4
Встановити мінімальну кількість днів між змінами пароля
\fIДНІ\fR\&. Нульове значення для цього поля вказує, що користувач може змінювати пароль будь\-коли\&.
.RE
.PP
\fB\-M\fR, \fB\-\-maxdays\fR \fIМАКСИМАЛЬНО_ДНІВ\fR
.RS 4
Встановити максимальну кількість днів, протягом яких буде чинним пароль\&. Якщо
\fIМАКСИМАЛЬНО_ДНІВ\fR
разом із
\fIОСТАННІЙ_ДЕНЬ\fR
буде меншим за поточну дату, система проситиме користувача змінити пароль, перш ніж він зможе увійти до свого облікового запису\&. Цю подію можна наперед запланувати за допомогою параметра
\fB\-W\fR, використання якого призведе до того, що система заздалегідь попереджуватиме користувача про потребу змінити пароль\&.
.sp
Передавання числа
\fI\-1\fR
у полі
\fIМАКСИМАЛЬНО_ДНІВ\fR
призведе до вилучення перевірки чинності паролів\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR \fIКАТАЛОГ_CHROOT\fR
.RS 4
Apply changes in the
\fICHROOT_DIR\fR
directory and use the configuration files from the
\fICHROOT_DIR\fR
directory\&. Only absolute paths are supported\&.
.RE
.PP
\fB\-W\fR, \fB\-\-warndays\fR \fIДНІ\fR
.RS 4
Встановити кількість днів між попередженням про потребу у зміні пароля і завершенням строку дії пароля\&. Параметром
\fIДНІ\fR
є кількість днів до завершення строку дії пароля, коли система попереджуватиме користувача про те, що пароль невдовзі доведеться змінити\&.
.RE
.PP
Якщо не буде вказано жодного параметра,
\fBchage\fR
буде запущено в інтерактивному режимі \(em програма покаже користувачеві поточні значення для усіх полів\&. Введіть нове значення, щоб змінити поле або нічого не вводьте, щоб лишити поточне значення\&. Поточне значення буде взято у квадратні дужки (\fI[ ]\fR)\&.
.SH "ЗАУВАЖЕННЯ"
.PP
Для роботи програми
\fBchage\fR
потрібна доступність файла прихованих паролів\&.
.PP
Програма chage повідомлятиме дані лише на основі файла паролів shadow\&. Таким чином, налаштування з інших джерел (наприклад, LDAP або порожнього поля хешу пароля з файла passwd), які впливають на вхід користувачів до системи, не буде показано у виведених chage даних\&.
.PP
Крім того, програма
\fBchage\fR
не повідомлятиме про несумісності у файлах shadow і passwd (наприклад, про те, що у файлі passwd немає якогось запису)\&. Для пошуку подібних несумісностей можна скористатися програмою
\fBpwck\fR\&.
.PP
Користуватися командою
\fBchage\fR
може лише користувач root, окрім варіанта з параметром
\fB\-l\fR, яким може скористатися непривілейований користувач для отримання даних щодо строку дії власного пароля або облікового запису\&.
.SH "НАЛАШТУВАННЯ"
.PP
Вказані нижче змінні налаштувань у
/etc/login\&.defs
змінюють поведінку цього інструмента:
.SH "ФАЙЛИ"
.PP
/etc/passwd
.RS 4
Відомості щодо облікових записів користувача\&.
.RE
.PP
/etc/shadow
.RS 4
Відомості щодо захищених облікових записів користувачів\&.
.RE
.SH "ЗНАЧЕННЯ ВИХОДУ"
.PP
Команда
\fBchage\fR
завершує роботу із такими значеннями:
.PP
\fI0\fR
.RS 4
успіх
.RE
.PP
\fI1\fR
.RS 4
відмовлено у доступі
.RE
.PP
\fI2\fR
.RS 4
некоректний синтаксис команди
.RE
.PP
\fI15\fR
.RS 4
не вдалося знайти файл прихованих паролів
.RE
.SH "ДИВ\&. ТАКОЖ"
.PP
\fBpasswd\fR(5),
\fBshadow\fR(5)\&.
