'\" t
.\"     Title: chfn
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/11/2022
.\"    Manual: Команди користувача
.\"    Source: shadow-utils 4.13
.\"  Language: Ukrainian
.\"
.TH "chfn" "1" "08/11/2022" "shadow\-utils 4\&.13" "Команди користувача"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
chfn \- зміна справжнього імені користувача і відомостей щодо нього
.SH "КОРОТКИЙ ОГЛЯД"
.HP \w'\fBchfn\fR\ 'u
\fBchfn\fR [\fIпараметри\fR] [\fIЗАПИС\fR]
.SH "ОПИС"
.PP
Команда
\fBchfn\fR
змінює повне ім\*(Aqя користувача, номер кімнати в офісі, номер телефону в офісі і дані щодо домашнього телефону для облікового запису користувача\&. Ці дані, зазвичай, виводить
\fBfinger\fR(1)
та подібні програми\&. Звичайні користувачі можуть змінювати значення полів лише для власного облікового запису, відповідно до обмежень у
/etc/login\&.defs\&. (Типовими налаштуваннями користувачам заборонено змінювати власне повне ім\*(Aqя\&.) Надкористувач може змінювати будь\-яке поле будь\-якого облікового запису\&. Крім того, лише надкористувач може використовувати параметр
\fB\-o\fR
для зміни невизначених частин поля GECOS\&.
.PP
Ці поля не повинні містити двокрапок\&. Окрім поля
\fIother\fR, у полях не повинно міститися ком та знаків рівності\&. Також рекомендуємо уникати символів поза US\-ASCII, втім, примусово це обмеження застосовується лише до номерів телефонів\&. Поле
\fIother\fR
використовують для зберігання облікових даних, які використовують інші програми\&.
.SH "ПАРАМЕТРИ"
.PP
Параметри, які застосовують до команди
\fBchfn\fR, є такими:
.PP
\fB\-f\fR, \fB\-\-full\-name\fR \fIІМ\*(AqЯ_ПОВНІСТЮ\fR
.RS 4
Змінити повне ім\*(Aqя користувача\&.
.RE
.PP
\fB\-h\fR, \fB\-\-home\-phone\fR \fIДОМАШНІЙ_ТЕЛЕФОН\fR
.RS 4
Змінити домашній телефон користувача\&.
.RE
.PP
\fB\-o\fR, \fB\-\-other\fR \fIІНШЕ\fR
.RS 4
Змінити інші відомості GECOS користувача\&. Це поле використовують для зберігання облікових даних, які використовують інші програми, його вміст може змінювати надкористувач\&.
.RE
.PP
\fB\-r\fR, \fB\-\-room\fR \fIНОМЕР_КІМНАТИ\fR
.RS 4
Змінити номер кімнати користувача\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR \fIКАТАЛОГ_CHROOT\fR
.RS 4
Apply changes in the
\fICHROOT_DIR\fR
directory and use the configuration files from the
\fICHROOT_DIR\fR
directory\&. Only absolute paths are supported\&.
.RE
.PP
\fB\-u\fR, \fB\-\-help\fR
.RS 4
Показати довідкове повідомлення і завершити роботу\&.
.RE
.PP
\fB\-w\fR, \fB\-\-work\-phone\fR \fIРОБОЧИЙ_ТЕЛЕФОН\fR
.RS 4
Змінити робочий телефон користувача\&.
.RE
.PP
Якщо не буде вказано жодного параметра,
\fBchfn\fR
буде запущено в інтерактивному режимі \(em програма покаже користувачеві поточні значення для усіх полів\&. Введіть нове значення, щоб змінити поле або нічого не вводьте, щоб лишити поточне значення\&. Поточне значення буде взято у квадратні дужки (\fB[ ]\fR)\&. Без параметрів
\fBchfn\fR
попросить вказати поточний обліковий запис користувача\&.\&.
.SH "НАЛАШТУВАННЯ"
.PP
Вказані нижче змінні налаштувань у
/etc/login\&.defs
змінюють поведінку цього інструмента:
.SH "ФАЙЛИ"
.PP
/etc/login\&.defs
.RS 4
Налаштування комплексу для роботи з прихованими паролями\&.
.RE
.PP
/etc/passwd
.RS 4
Відомості щодо облікових записів користувача\&.
.RE
.SH "ДИВ\&. ТАКОЖ"
.PP
\fBchsh\fR(1),
\fBlogin.defs\fR(5),
\fBpasswd\fR(5)\&.
