'\" t
.\"     Title: chsh
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/11/2022
.\"    Manual: Команди користувача
.\"    Source: shadow-utils 4.13
.\"  Language: Ukrainian
.\"
.TH "chsh" "1" "08/11/2022" "shadow\-utils 4\&.13" "Команди користувача"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
chsh \- зміна оболонки входу
.SH "КОРОТКИЙ ОГЛЯД"
.HP \w'\fBchsh\fR\ 'u
\fBchsh\fR [\fIпараметри\fR] [\fIЗАПИС\fR]
.SH "ОПИС"
.PP
Команда
\fBchsh\fR
змінює оболонку входу користувача\&. Команда визначає назву початкової команди входу користувача\&. Звичайний користувач може змінювати оболонку входу лише для власного облікового запису; надкористувач може змінювати оболонку входу для будь\-якого облікового запису\&.
.SH "ПАРАМЕТРИ"
.PP
Параметри, які застосовують до команди
\fBchsh\fR, є такими:
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показати довідкове повідомлення і завершити роботу\&.
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR \fIКАТАЛОГ_CHROOT\fR
.RS 4
Apply changes in the
\fICHROOT_DIR\fR
directory and use the configuration files from the
\fICHROOT_DIR\fR
directory\&. Only absolute paths are supported\&.
.RE
.PP
\fB\-s\fR, \fB\-\-shell\fR \fIОБОЛОНКА\fR
.RS 4
Назва нової оболонки для входу користувача\&. Встановлення для цього поля порожнього значення призведе до того, що система вибере типову оболонку для входу\&.
.RE
.PP
Якщо не буде вказано параметра
\fB\-s\fR,
\fBchsh\fR
буде запущено в інтерактивному режимі \(em програма покаже користувачеві поточне значення для оболонки входу\&. Введіть нове значення, щоб змінити оболонку або нічого не вводьте, щоб лишити поточну\&. Поточну оболонку буде взято у квадратні дужки (\fI[ ]\fR)\&.
.SH "ЗАУВАЖЕННЯ"
.PP
Єдиним обмеженням, яке накладають на оболонку входу є те, що назва команди має бути частиною списку у
/etc/shells, якщо команду не викликано від імені надкористувача\&. Надкористувач може додавати будь\-яке значення\&. Власники облікових записів із обмеженою оболонкою для входу не може змінювати власну оболонку\&. З цієї причини не варто додавати
/bin/rsh
у
/etc/shells, оскільки випадкова зміна обмеженої командної оболонки призведе до повної заборони для користувача змінювати оболонку входу та початкову\&.
.SH "НАЛАШТУВАННЯ"
.PP
Вказані нижче змінні налаштувань у
/etc/login\&.defs
змінюють поведінку цього інструмента:
.SH "ФАЙЛИ"
.PP
/etc/passwd
.RS 4
Відомості щодо облікових записів користувача\&.
.RE
.PP
/etc/shells
.RS 4
Список чинних оболонок входу\&.
.RE
.PP
/etc/login\&.defs
.RS 4
Налаштування комплексу для роботи з прихованими паролями\&.
.RE
.SH "ДИВ\&. ТАКОЖ"
.PP
\fBchfn\fR(1),
\fBlogin.defs\fR(5),
\fBpasswd\fR(5)\&.
