'\" t
.\"     Title: gpasswd
.\"    Author: Rafal Maszkowski
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/11/2022
.\"    Manual: Команди користувача
.\"    Source: shadow-utils 4.13
.\"  Language: Ukrainian
.\"
.TH "gpasswd" "1" "08/11/2022" "shadow\-utils 4\&.13" "Команди користувача"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
gpasswd \- адміністрування /etc/group і /etc/gshadow
.SH "КОРОТКИЙ ОГЛЯД"
.HP \w'\fBgpasswd\fR\ 'u
\fBgpasswd\fR [\fIпараметр\fR] \fIгрупа\fR
.SH "ОПИС"
.PP
Команду
\fBgpasswd\fR
використовують для адміністрування
/etc/group, and /etc/gshadow\&. У кожної групи може складатися з
адміністраторів,
учасників і мати пароль\&.
.PP
Адміністратори системи можуть скористатися параметром
\fB\-A\fR
для визначення адміністраторів групи і параметром
\fB\-M\fR
для визначення учасників\&. Вони мають усі права адміністраторів і учасників груп\&.
.PP
Виклик
\fBgpasswd\fR, якщо його здійснює групи \(Foадміністратор групи\(Fc лише із назвою групи, призведе до запиту щодо нового пароля для групи
\fIгрупа\fR\&.
.PP
Якщо пароль встановлено, учасники зможуть продовжити користуватися
\fBnewgrp\fR(1)
без пароля, а тим, хто не є учасником, доведеться вказати пароль\&.
.SS "Нотатки щодо паролів груп"
.PP
Паролі груп мають неусувну проблему захисту, оскільки пароль знатимуть декілька осіб\&. Втім, групи є корисним інструментом для забезпечення взаємодії між різними користувачами\&.
.SH "ПАРАМЕТРИ"
.PP
Окрім параметрів
\fB\-A\fR
і
\fB\-M\fR, параметри не можна поєднувати\&.
.PP
Параметри, які застосовують до команди
\fBgpasswd\fR, є такими:
.PP
\fB\-a\fR, \fB\-\-add\fR \fIкористувач\fR
.RS 4
Додати
\fIкористувач\fR
до іменованого
\fIгрупа\fR\&.
.RE
.PP
\fB\-d\fR, \fB\-\-delete\fR \fIкористувач\fR
.RS 4
Вилучити
\fIкористувач\fR
з іменованого
\fIгрупа\fR\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показати довідкове повідомлення і завершити роботу\&.
.RE
.PP
\fB\-Q\fR, \fB\-\-root\fR \fIКАТАЛОГ_CHROOT\fR
.RS 4
Apply changes in the
\fICHROOT_DIR\fR
directory and use the configuration files from the
\fICHROOT_DIR\fR
directory\&. Only absolute paths are supported\&.
.RE
.PP
\fB\-r\fR, \fB\-\-remove\-password\fR
.RS 4
Вилучити пароль із вказаної за назвою групи
\fIгрупа\fR\&. Пароль групи стане порожнім\&. Скористатися
\fBnewgrp\fR
для долучення до іменованої групи
\fIгрупа\fR
зможуть лише учасники групи\&.
.RE
.PP
\fB\-R\fR, \fB\-\-restrict\fR
.RS 4
Обмежити доступ до вказаної за назвою групи
\fIгрупа\fR\&. Для пароля групи буде встановлено значення \(Fo!\(Fc\&. Скористатися
\fBnewgrp\fR
для долучення до іменованої групи
\fIгрупа\fR
зможуть лише учасники групи з паролем\&.
.RE
.PP
\fB\-A\fR, \fB\-\-administrators\fR \fIкористувач\fR,\&.\&.\&.
.RS 4
Встановити список адміністративних користувачів\&.
.RE
.PP
\fB\-M\fR, \fB\-\-members\fR \fIкористувач\fR,\&.\&.\&.
.RS 4
Встановити список учасників групи\&.
.RE
.SH "ЗАСТЕРЕЖЕННЯ"
.PP
Цей інструмент працює лише з файлами
/etc/group
and /etc/gshadow files\&.
Отже, за його допомогою ви не зможете внести зміни до груп NIS або LDAP\&. Зміни доведеться вносити на відповідному сервері\&.
.SH "НАЛАШТУВАННЯ"
.PP
Вказані нижче змінні налаштувань у
/etc/login\&.defs
змінюють поведінку цього інструмента:
.SH "ФАЙЛИ"
.PP
/etc/group
.RS 4
Відомості щодо груп облікових записів\&.
.RE
.PP
/etc/gshadow
.RS 4
Відомості щодо захищених груп облікових записів\&.
.RE
.SH "ДИВ\&. ТАКОЖ"
.PP
\fBnewgrp\fR(1),
\fBgroupadd\fR(8),
\fBgroupdel\fR(8),
\fBgroupmod\fR(8),
\fBgrpck\fR(8),
\fBгрупа\fR(5), \fBgshadow\fR(5)\&.
