'\" t
.\"     Title: groups
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/11/2022
.\"    Manual: Команди користувача
.\"    Source: shadow-utils 4.13
.\"  Language: Ukrainian
.\"
.TH "groups" "1" "08/11/2022" "shadow\-utils 4\&.13" "Команди користувача"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
groups \- показ поточних назв груп
.SH "КОРОТКИЙ ОГЛЯД"
.HP \w'\fBgroups\fR\ 'u
\fBgroups\fR [\fIкористувач\fR]
.SH "ОПИС"
.PP
Команда
\fBgroups\fR
виводить назви або значення ідентифікаторів поточних груп\&. Якщо у значення немає відповідного запису у
/etc/group, значення буде виведено як числове значення групи\&. Використання необов\*(Aqязкового параметра
\fIкористувач\fR
призведе до показу груп іменованого користувача\&.
.SH "ЗАУВАЖЕННЯ"
.PP
Для систем, у яких не передбачено підтримку додаткових груп (див\&.
\fBinitgroups\fR(3)) буде показано відомості з
/etc/group\&. Користувач має скористатися
\fBnewgrp\fR
або
\fBsg\fR
для зміни його поточного справжнього і ефективного ідентифікатора групи\&.
.SH "ФАЙЛИ"
.PP
/etc/group
.RS 4
Відомості щодо груп облікових записів\&.
.RE
.SH "ДИВ\&. ТАКОЖ"
.PP
\fBnewgrp\fR(1),
\fBgetgid\fR(2),
\fBgetgroups\fR(2),
\fBgetuid\fR(2),
\fBinitgroups\fR(3)\&.
