'\" t
.\"     Title: login
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/11/2022
.\"    Manual: Команди користувача
.\"    Source: shadow-utils 4.13
.\"  Language: Ukrainian
.\"
.TH "login" "1" "08/11/2022" "shadow\-utils 4\&.13" "Команди користувача"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
login \- розпочати сеанс у системі
.SH "КОРОТКИЙ ОГЛЯД"
.HP \w'\fBlogin\fR\ 'u
\fBlogin\fR [\-p] [\-h\ \fIhost\fR] [\fIкористувач\fR] [\fIСЕРЕДОВИЩЕ=ЗМІННА\fR...]
.HP \w'\fBlogin\fR\ 'u
\fBlogin\fR [\-p] [\-h\ \fIhost\fR] \-f \fIкористувач\fR
.HP \w'\fBlogin\fR\ 'u
\fBlogin\fR [\-p] \-r\ \fIhost\fR
.SH "ОПИС"
.PP
Програму
\fBlogin\fR
призначено для встановлення нового сеансу роботи з системою\&. Зазвичай, її виклик відбувається автоматично у відповідь на запит
\fIlogin:\fR
у терміналі користувача\&.
\fBlogin\fR
може бути спеціалізованою для оболонки і непридатною до виклику у форматі підлеглого процесу\&. Якщо програму викликано з оболонки,
\fBlogin\fR
має бути виконано як
\fBexec login\fR, що спричинить вихід користувача з поточної оболонки (і, таким чином, запобігатиме поверненню користувача, який увійшов до системи, до сеансу того, хто віддав команду)\&. Спроба виконати
\fBlogin\fR
з будь\-якої командної оболонки, окрім оболонки входу, призведе до виведення повідомлення про помилку\&.
.PP
Після цього, користувачеві, якщо це потрібно, буде запропоновано ввести пароль\&. Відтворення пароля на екрані буде вимкнено, щоб запобігти розкриттю пароля\&. Кількість спроб буде суттєво обмежено\&. При перевищенні граничної кількості спроб ввести пароль
\fBlogin\fR
завершить роботу і перерве зв\*(Aqязок для обміну даними\&.
.PP
Якщо для вашого облікового запису було увімкнено застарівання паролів, програма може попросити вас ввести новий пароль, перш ніж продовжити роботу\&. Вам доведеться ввести старий і новий пароль, перш ніж продовжити роботу\&. Будь ласка, зверніться до підручника з
\fBpasswd\fR(1), щоб дізнатися більше\&.
.PP
Після успішного входу до системи вас буде проінформовано про усі повідомлення системи та наявність пошти\&. Ви можете вимкнути виведення даних до файла повідомлень системи,
/etc/motd, створенням файла нульового розміру
\&.hushlogin
у вашому каталозі для входу\&. Повідомленням про пошту буде одне з таких повідомлень: \(Fo\fIВи отримали нову пошту\&.\fR\(Fc, \(Fo\fIДля вас є пошта\&.\fR\(Fc або \(Fo\fIПошти немає\&.\fR\(Fc, відповідно до стану вашої поштової скриньки\&.
.PP
Ваші ідентифікатори користувача і групи буде встановлено відповідно до значень у файлі
/etc/passwd\&. Значення
\fB$HOME\fR,
\fB$SHELL\fR,
\fB$PATH\fR,
\fB$LOGNAME\fR
і
\fB$MAIL\fR
буде встановлено відповідно до відповідних полів у записі пароля\&. Значення ulimit, umask і nice також може бути встановлено відповідно до записів у полі GECOS\&.
.PP
У деяких встановлених системах змінну середовища
\fB$TERM\fR
буде ініціалізовано значенням типу термінала у вашому рядку tty, як це вказано у
/etc/ttytype\&.
.PP
Також може бути виконано скрипт ініціалізації для вашого інтерпретатора командного рядка\&. Будь ласка, зверніться до відповідного розділу підручника, щоб дізнатися більше про цю функціональну можливість\&.
.PP
Вхід до підсистеми буде позначено наявністю \(Fo*\(Fc як першого символу оболонки входу\&. Заданий домашній каталог буде використано як кореневий каталог нової файлової системи, до якої користувач насправді увійшов\&.
.PP
Програма
\fBlogin\fR
НЕ відповідає за вилучення записів користувачів з файла utmp\&. За чищення видимого власника сеансу термінала відповідають
\fBgetty\fR(8)
і
\fBinit\fR(8)\&. Якщо ви користуєтеся
\fBlogin\fR
з запиту командної оболонки без
\fBexec\fR, використаний вами обліковий запис користувача продовжуватиме \(Foпрацювати\(Fc у системі, навіть після того, як ви вийдете з \(Foпідлеглого сеансу\(Fc\&.
.SH "ПАРАМЕТРИ"
.PP
\fB\-f\fR
.RS 4
Не виконувати розпізнавання, користувача попередньо розпізнано\&.
.sp
Зауваження: у цьому випадку обов\*(Aqязковим є
\fIкористувач\fR\&.
.RE
.PP
\fB\-h\fR
.RS 4
Назва віддаленого вузла для цього входу до облікового запису\&.
.RE
.PP
\fB\-p\fR
.RS 4
Зберегти середовище\&.
.RE
.PP
\fB\-r\fR
.RS 4
Виконати протокол автоматичного входу для rlogin\&.
.RE
.PP
Параметри
\fB\-r\fR,
\fB\-h\fR
і
\fB\-f\fR
використовують, лише якщо
\fBlogin\fR
викликано від імені користувача root\&.
.SH "ЗАСТЕРЕЖЕННЯ"
.PP
У цієї версії
\fBlogin\fR
багато параметрів збирання\&. У певній збірці може бути використано лише частину з них\&.
.PP
Розташування файлів є різним у різних конфігураціях системи\&.
.PP
Програма
\fBlogin\fR
НЕ відповідає за вилучення записів користувачів з файла utmp\&. За чищення видимого власника сеансу термінала відповідають
\fBgetty\fR(8)
і
\fBinit\fR(8)\&. Якщо ви користуєтеся
\fBlogin\fR
з запиту командної оболонки без
\fBexec\fR, використаний вами обліковий запис користувача продовжуватиме \(Foпрацювати\(Fc у системі, навіть після того, як ви вийдете з \(Foпідлеглого сеансу\(Fc\&.
.PP
Як і з будь\-якою програмою, вигляд
\fBlogin\fR
може бути підроблено\&. Якщо до комп\*(Aqютера мають фізичний доступ сторонні користувачі, зловмисник може скористатися цим для отримання пароля наступного за ним користувача комп\*(Aqютера\&. У Linux користувачі можуть скористатися механізмом SAK для ініціалізації надійного шляху і запобігання атакам цього типу\&.
.SH "НАЛАШТУВАННЯ"
.PP
Вказані нижче змінні налаштувань у
/etc/login\&.defs
змінюють поведінку цього інструмента:
.SH "ФАЙЛИ"
.PP
/var/run/utmp
.RS 4
Список поточних сеансів входу до системи\&.
.RE
.PP
/var/log/wtmp
.RS 4
Список попередніх сеансів входу до системи\&.
.RE
.PP
/etc/passwd
.RS 4
Відомості щодо облікових записів користувача\&.
.RE
.PP
/etc/shadow
.RS 4
Відомості щодо захищених облікових записів користувачів\&.
.RE
.PP
/etc/motd
.RS 4
Файл повідомлень дня системи\&.
.RE
.PP
/etc/nologin
.RS 4
Запобігати спробам входу до системи користувачів, відмінних від root\&.
.RE
.PP
/etc/ttytype
.RS 4
Список типів терміналів\&.
.RE
.PP
$HOME/\&.hushlogin
.RS 4
Придушити виведення системних повідомлень\&.
.RE
.PP
/etc/login\&.defs
.RS 4
Налаштування комплексу для роботи з прихованими паролями\&.
.RE
.SH "ДИВ\&. ТАКОЖ"
.PP
\fBmail\fR(1),
\fBpasswd\fR(1),
\fBsh\fR(1),
\fBsu\fR(1),
\fBlogin.defs\fR(5),
\fBnologin\fR(5),
\fBpasswd\fR(5),
\fBsecuretty\fR(5),
\fBgetty\fR(8)\&.
