'\" t
.\"     Title: passwd
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/11/2022
.\"    Manual: Команди користувача
.\"    Source: shadow-utils 4.13
.\"  Language: Ukrainian
.\"
.TH "passwd" "1" "08/11/2022" "shadow\-utils 4\&.13" "Команди користувача"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
passwd \- зміна пароля користувача
.SH "КОРОТКИЙ ОГЛЯД"
.HP \w'\fBpasswd\fR\ 'u
\fBpasswd\fR [\fIпараметри\fR] [\fIЗАПИС\fR]
.SH "ОПИС"
.PP
Команда
\fBpasswd\fR
змінює паролі до облікових записів користувачів\&. Звичайний користувач може змінювати пароль лише для власного облікового запису, а надкористувач може змінювати пароль для будь\-якого облікового запису\&.
\fBpasswd\fR
також змінює період чинності облікового запису або пов\*(Aqязаного з ним пароля\&.
.SS "Зміни паролів"
.PP
Спочатку програма попросить користувача ввести старий пароль, якщо такий існує\&. Потім цей пароль буде зашифровано і порівняно із збереженим паролем\&. Користувачу буде надано лише одну спробу ввести правильний пароль\&. Надкористувач може обійти цей крок, тому може змінювати забуті паролі\&.
.PP
Після введення пароля буде перевірено дані щодо віку пароля, щоб визначити, чи може користувач змінювати пароль на поточний момент часу\&. Якщо користувач не може цього робити,
\fBpasswd\fR
відмовить у зміні пароля і завершить роботу\&.
.PP
Потім програма попросить користувача ввести пароль\-замінник двічі\&. Друге введене значення буде порівняно із першим \(em вони мають бути однаковими, щоб пароль було змінено\&.
.PP
Далі, пароль буде перевірено на складність\&. Загальним правилом є те, що пароль має складатися з від 6 до 8 символів, включаючи один або декілька символів з кожного з таких наборів:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
малі літери латинської абетки
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
цифри від 0 до 9
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
символи пунктуації
.RE
.PP
До пароля не можна включати типові символи вилучення або витирання системи\&.
\fBpasswd\fR
не прийме пароля, який не є достатньо складним\&.
.SS "Підказки для паролів користувача"
.PP
Захист пароля залежить від складності алгоритму шифрування та розміру простору ключів\&. Застарілий спосіб шифрування системи
\fIUNIX\fR
засновано на алгоритмі DES NBS\&. На сьогодні, рекомендують сучасніші методи (див\&.
\fBENCRYPT_METHOD\fR)\&. Розмір простору ключів залежить від випадковості пароля, яку було вибрано\&.
.PP
Послаблення захисту паролями, зазвичай, є результатом необдуманого вибору пароля або поводження з ним\&. З цієї причини, не слід вибирати пароль зі словника або десь його записувати\&. Не слід також вибирати для пароля власне ім\*(Aqя, номер водійського посвідчення, дату народження або назву вулиці, на якій ви мешкаєте\&. Вибір будь\-якого з цих варіантів може призвести до вгадування пароля і компрометації захисту системи\&.
.PP
Поради щодо вибору надійного пароля можна знайти на сторінці https://uk\&.wikipedia\&.org/wiki/Надійність_пароля
.SH "ПАРАМЕТРИ"
.PP
Параметри, які застосовують до команди
\fBpasswd\fR, є такими:
.PP
\fB\-a\fR, \fB\-\-all\fR
.RS 4
Цим параметром можна скористатися лише у поєднанні із
\fB\-S\fR\&. Його використання призведе до показу стану для усіх користувачів\&.
.RE
.PP
\fB\-d\fR, \fB\-\-delete\fR
.RS 4
Вилучити пароль користувача (зробити його порожнім)\&. Це швидкий спосіб вимкнути пароль для облікового запису\&. Команда зробити іменований обліковий запис безпарольним\&.
.RE
.PP
\fB\-e\fR, \fB\-\-expire\fR
.RS 4
Негайно завершити строк дії пароля облікового запису\&. Результатом є те, що система вимагатиме від користувача змінити пароль під час наступного входу до системи\&.
.RE
.PP
\fB\-h\fR, \fB\-\-help\fR
.RS 4
Показати довідкове повідомлення і завершити роботу\&.
.RE
.PP
\fB\-i\fR, \fB\-\-inactive\fR \fIНЕАКТИВНИЙ\fR
.RS 4
Цей параметр використовують для вимикання облікового запису за вказану кількість днів після завершення строку дії пароля\&. Після того, як мине
\fIНЕАКТИВНИЙ\fR
днів з моменту завершення строку дії пароля, користувач не зможе увійти до облікового запису\&.
.RE
.PP
\fB\-k\fR, \fB\-\-keep\-tokens\fR
.RS 4
Вказати, що зміну пароля має бути виконано лише для жетонів (паролів) розпізнавання, строк дії яких вичерпано\&. Користувач бажає зберегти попередню дію жетонів, строк дії яких не вичерпано\&.
.RE
.PP
\fB\-l\fR, \fB\-\-lock\fR
.RS 4
Заблокувати пароль іменованого облікового запису\&. За допомогою цього параметра можна вимкнути пароль, змінивши його на значення, яке не відповідає зашифрованому значенню (буде додано \(aa!\(aa на початку пароля)\&.
.sp
Зауважте, що це не призведе до вимикання облікового запису\&. Користувач зможе входити до системи за допомогою іншого жетона розпізнавання (наприклад ключа SSH)\&. Щоб вимкнути обліковий запис, адміністраторам слід користуватися
\fBusermod \-\-expiredate 1\fR
(ця команда встановить для дати завершення строку дії облікового запису значення 2 січня 1970 року)\&.
.sp
Користувачі із заблокованим паролем не зможуть змінювати власний пароль\&.
.RE
.PP
\fB\-n\fR, \fB\-\-mindays\fR \fIДНІ\fR
.RS 4
Встановити мінімальну кількість днів між змінами пароля
\fIДНІ\fR\&. Нульове значення для цього поля вказує, що користувач може змінювати пароль будь\-коли\&.
.RE
.PP
\fB\-q\fR, \fB\-\-quiet\fR
.RS 4
Режим без повідомлень\&.
.RE
.PP
\fB\-r\fR, \fB\-\-repository\fR \fIСХОВИЩЕ\fR
.RS 4
змінити пароль у сховищі
\fIСХОВИЩЕ\fR
.RE
.PP
\fB\-R\fR, \fB\-\-root\fR \fIКАТАЛОГ_CHROOT\fR
.RS 4
Apply changes in the
\fICHROOT_DIR\fR
directory and use the configuration files from the
\fICHROOT_DIR\fR
directory\&. Only absolute paths are supported\&.
.RE
.PP
\fB\-S\fR, \fB\-\-status\fR
.RS 4
Вивести дані щодо стану облікового запису\&. Дані щодо стану складаються з 7 полів\&. Першим полем є назва облікового запису користувача\&. Друге поле вказує на те, чи є обліковий запис таким, для якого заблоковано пароль (L), немає пароля (NP) або має придатний до користування пароль (P)\&. Третє поле задає дату останньої зміни пароля\&. Наступними чотирма полями є мінімальний вік, максимальний вік, період попередження та період неактивності для пароля\&. Ці значення віку виражаються у днях\&.
.RE
.PP
\fB\-u\fR, \fB\-\-unlock\fR
.RS 4
Розблокувати пароль для іменованого облікового запису\&. Цей параметр повторно вмикає пароль, замінюючи пароль на попереднє його значення (на значення до використання параметра
\fB\-l\fR)\&.
.RE
.PP
\fB\-w\fR, \fB\-\-warndays\fR \fIДНІ\fR
.RS 4
Встановити кількість днів між попередженням про потребу у зміні пароля і завершенням строку дії пароля\&. Параметром
\fIДНІ\fR
є кількість днів до завершення строку дії пароля, коли система попереджуватиме користувача про те, що пароль невдовзі доведеться змінити\&.
.RE
.PP
\fB\-x\fR, \fB\-\-maxdays\fR \fIМАКСИМАЛЬНО_ДНІВ\fR
.RS 4
Встановити максимальну кількість днів, протягом яких пароль лишатиметься чинним\&. Щойно мине
\fIМАКСИМАЛЬНО_ДНІВ\fR, система вимагатиме від користувача змінити пароль\&.
.sp
Передавання числа
\fI\-1\fR
у полі
\fIМАКСИМАЛЬНО_ДНІВ\fR
призведе до вилучення перевірки чинності паролів\&.
.RE
.SH "ЗАСТЕРЕЖЕННЯ"
.PP
Перевірка складності пароля може бути різною у різних системах\&. Система вимагатиме вибрати пароль, який буде достатньо складним на думку її розробників\&.
.PP
Можливо, користувачі не зможуть змінити свій пароль у системі, якщо увімкнено NIS, і користувачі не увійшли до сервера NIS\&.
.SH "НАЛАШТУВАННЯ"
.PP
Вказані нижче змінні налаштувань у
/etc/login\&.defs
змінюють поведінку цього інструмента:
.SH "ФАЙЛИ"
.PP
/etc/passwd
.RS 4
Відомості щодо облікових записів користувача\&.
.RE
.PP
/etc/shadow
.RS 4
Відомості щодо захищених облікових записів користувачів\&.
.RE
.PP
/etc/login\&.defs
.RS 4
Налаштування комплексу для роботи з прихованими паролями\&.
.RE
.SH "ЗНАЧЕННЯ ВИХОДУ"
.PP
Команда
\fBpasswd\fR
завершує роботу із такими значеннями:
.PP
\fI0\fR
.RS 4
успіх
.RE
.PP
\fI1\fR
.RS 4
відмовлено у доступі
.RE
.PP
\fI2\fR
.RS 4
некоректне поєднання параметрів
.RE
.PP
\fI3\fR
.RS 4
неочікувана помилка, нічого не виконано
.RE
.PP
\fI4\fR
.RS 4
неочікувана помилка, не вистачає файла
passwd
.RE
.PP
\fI5\fR
.RS 4
файл
passwd
зайнято, повторіть спробу
.RE
.PP
\fI6\fR
.RS 4
некоректний аргумент параметра
.RE
.SH "ДИВ\&. ТАКОЖ"
.PP
\fBchpasswd\fR(8),
\fBpasswd\fR(5),
\fBshadow\fR(5),
\fBlogin.defs\fR(5),
\fBusermod\fR(8)\&.
