'\" t
.\"     Title: sg
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/11/2022
.\"    Manual: Команди користувача
.\"    Source: shadow-utils 4.13
.\"  Language: Ukrainian
.\"
.TH "sg" "1" "08/11/2022" "shadow\-utils 4\&.13" "Команди користувача"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
sg \- виконання команди від імені іншого ідентифікатора групи
.SH "КОРОТКИЙ ОГЛЯД"
.HP \w'\fBsg\fR\ 'u
\fBsg\fR [\-] [група\ [\-c]\ команда]
.SH "ОПИС"
.PP
Команда
\fBsg\fR
працює подібно до команди
\fBnewgrp\fR, але приймає команду\&. Цю команду буде виконано за допомогою оболонки
/bin/sh\&. У більшості оболонок, з яких ви можете запустити
\fBsg\fR, вам доведеться брати багатослівні команди у лапки\&. Іншою відмінністю між
\fBnewgrp\fR
і
\fBsg\fR
є те, що деякі оболонки обробляють
\fBnewgrp\fR
по\-особливому, замінюючи себе новим екземпляром оболонки, який створює
\fBnewgrp\fR\&. Такого не трапляється з
\fBsg\fR\&. Отже, після виходу з команди
\fBsg\fR
ви повернетеся до вашого попереднього ідентифікатора групи\&.
.SH "НАЛАШТУВАННЯ"
.PP
Вказані нижче змінні налаштувань у
/etc/login\&.defs
змінюють поведінку цього інструмента:
.SH "ФАЙЛИ"
.PP
/etc/passwd
.RS 4
Відомості щодо облікових записів користувача\&.
.RE
.PP
/etc/shadow
.RS 4
Відомості щодо захищених облікових записів користувачів\&.
.RE
.PP
/etc/group
.RS 4
Відомості щодо груп облікових записів\&.
.RE
.PP
/etc/gshadow
.RS 4
Відомості щодо захищених груп облікових записів\&.
.RE
.SH "ДИВ\&. ТАКОЖ"
.PP
\fBid\fR(1),
\fBlogin\fR(1),
\fBnewgrp\fR(1),
\fBsu\fR(1),
\fBgpasswd\fR(1),
\fBгрупа\fR(5), \fBgshadow\fR(5)\&.
