'\" t
.\"     Title: su
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/11/2022
.\"    Manual: Команди користувача
.\"    Source: shadow-utils 4.13
.\"  Language: Ukrainian
.\"
.TH "su" "1" "08/11/2022" "shadow\-utils 4\&.13" "Команди користувача"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
su \- зміна ідентифікатора користувача або набуття прав надкористувача
.SH "КОРОТКИЙ ОГЛЯД"
.HP \w'\fBsu\fR\ 'u
\fBsu\fR [\fIпараметри\fR] [\fI\-\fR] [\fIкористувач\fR\ [\ \fIаргументи\fR\ ]]
.SH "ОПИС"
.PP
Команду
\fBsu\fR
використовують для набуття прав іншого користувача під час робочого сеансу у системі\&. Якщо команду викликано без
\fBкористувач\fR,
\fBsu\fR, типово, надає доступ до облікового запису надкористувача\&. Параметром
\fB\-\fR
можна скористатися для забезпечення середовища, подібного до того, яке б мав отримати користувач, який увійшов до системи безпосередньо\&. Параметром
\fB\-c\fR
можна скористатися для того, щоб більшість командних оболонок вважали наступний аргумент командою\&.
.PP
Параметри буде розпізнано усюди у списку аргументів\&. Ви можете скористатися аргументом
\fB\-\-\fR, щоб припинити обробку аргументів\&. Параметр
\fB\-\fR
є особливим: програма розпізнає його також після
\fB\-\-\fR, але його слід розташувати перед
\fBкористувач\fR\&.
.PP
Програма попросить користувача ввести пароль, якщо у цьому є потреба\&. Введення некоректного пароля призведе до виведення повідомлення про помилку\&. Усі спроби, коректні і некоректні, буде записано до журналу для виявлення спроб зловмисників проникнути у систему\&.
.PP
Поточне середовище буде передано новій оболонці\&. Значення
\fB$PATH\fR
буде скинуто до
/bin:/usr/bin
для звичайних користувачів або
/sbin:/bin:/usr/sbin:/usr/bin
для надкористувача\&. Це значення можна змінити за допомогою визначень
\fBENV_PATH\fR
і
\fBENV_SUPATH\fR
у
/etc/login\&.defs\&.
.PP
Вхід до підсистеми буде позначено наявністю \(Fo*\(Fc як першого символу оболонки входу\&. Заданий домашній каталог буде використано як кореневий каталог нової файлової системи, до якої користувач насправді увійшов\&.
.SH "ПАРАМЕТРИ"
.PP
Параметри, які застосовують до команди
\fBsu\fR, є такими:
.PP
\fB\-c\fR, \fB\-\-command\fR \fIКОМАНДА\fR
.RS 4
Вказати команду, яку буде викликано командною оболонкою за допомогою її
\fB\-c\fR\&.
.sp
У виконаної команди не буде керівного термінала\&. Цей параметр не можна використовувати для виконання інтерактивних програм, яким потрібне для керування термінал\&.
.RE
.PP
\fB\-\fR, \fB\-l\fR, \fB\-\-login\fR
.RS 4
Надає середовище, яке є подібним до середовища, яке мав би отримати користувач після безпосереднього входу до системи\&.
.sp
Якщо використано параметр
\fB\-\fR, його має бути вказано перед будь\-яким
\fBкористувач\fR\&. З міркувань сумісності рекомендуємо використовувати його як останній параметр, до
\fBкористувач\fR\&. Для інших форм (\fB\-l\fR
і
\fB\-\-login\fR) цього обмеження не передбачено\&.
.RE
.PP
\fB\-s\fR, \fB\-\-shell\fR \fIОБОЛОНКА\fR
.RS 4
Оболонка, яку буде викликано\&.
.sp
Викликану оболонку буде вибрано з таких варіантів (варіанти із вищим пріоритетом наведено першими):
.PP
.RS 4
Командна оболонка, яку вказано за допомогою \-\-shell\&.
.RE
.PP
.RS 4
Якщо використано параметр
\fB\-\-preserve\-environment\fR, оболонка, яку вказано за допомогою змінної середовища
\fB$SHELL\fR\&.
.RE
.PP
.RS 4
Оболонки, на яку вказує запис
/etc/passwd
для вибраного користувача\&.
.RE
.PP
.RS 4
/bin/sh, якщо оболонку не вдасться знайти у жоден із вказаних вище способів\&.
.RE
.sp
Якщо командну оболонку вказаного користувача обмежено (тобто вмісту поля оболонки запису цього користувача у
/etc/passwd
немає у списку
/etc/shells), параметр
\fB\-\-shell\fR
та змінну середовища
\fB$SHELL\fR
не буде взято до уваги, якщо
\fBsu\fR
не викликано від імені користувача root\&.
.RE
.PP
\fB\-m\fR, \fB\-p\fR, \fB\-\-preserve\-environment\fR
.RS 4
Зберегти поточне середовище, окрім
.PP
\fB$PATH\fR
.RS 4
відновлено початкове значення за параметром
/etc/login\&.defs
\fBENV_PATH\fR
або
\fBENV_SUPATH\fR
(див\&. нижче);
.RE
.PP
\fB$IFS\fR
.RS 4
відновлено до значення
\(Fo<space><tab><newline>\(Fc, якщо було встановлено інше значення\&.
.RE
.sp
Якщо у користувача призначення командну оболонку обмежено, цей параметр ні на що не вплине (якщо
\fBsu\fR
не викликано від імені користувача root)\&.
.sp
Зауважте, що типовою поведінкою для середовища є така:
.PP
.RS 4
Буде відновлено початкові значення змінних середовища
\fB$HOME\fR,
\fB$SHELL\fR,
\fB$USER\fR,
\fB$LOGNAME\fR,
\fB$PATH\fR
і
\fB$IFS\fR\&.
.RE
.PP
.RS 4
Якщо не використано
\fB\-\-login\fR, середовище буде скопійовано, окрім вказаних вище змінних\&.
.RE
.PP
.RS 4
Якщо використано
\fB\-\-login\fR, змінні середовища
\fB$TERM\fR,
\fB$COLORTERM\fR,
\fB$DISPLAY\fR
і
\fB$XAUTHORITY\fR
буде скопійовано, якщо було встановлено їхні значення\&.
.RE
.PP
.RS 4
Якщо використано
\fB\-\-login\fR, значення змінних середовища
\fB$TZ\fR,
\fB$HZ\fR
і
\fB$MAIL\fR
буде встановлено за параметрами
/etc/login\&.defs
\fBENV_TZ\fR,
\fBENV_HZ\fR,
\fBMAIL_DIR\fR
і
\fBMAIL_FILE\fR
(див\&. нижче)\&.
.RE
.PP
.RS 4
Якщо використано
\fB\-\-login\fR, значення для інших змінних середовища можна встановити за допомогою файла
\fBENVIRON_FILE\fR
(див\&. нижче)\&.
.RE
.RE
.SH "ЗАСТЕРЕЖЕННЯ"
.PP
У цієї версії
\fBsu\fR
багато параметрів збирання\&. У певній збірці може бути використано лише частину з них\&.
.SH "НАЛАШТУВАННЯ"
.PP
Вказані нижче змінні налаштувань у
/etc/login\&.defs
змінюють поведінку цього інструмента:
.SH "ФАЙЛИ"
.PP
/etc/passwd
.RS 4
Відомості щодо облікових записів користувача\&.
.RE
.PP
/etc/shadow
.RS 4
Відомості щодо захищених облікових записів користувачів\&.
.RE
.PP
/etc/login\&.defs
.RS 4
Налаштування комплексу для роботи з прихованими паролями\&.
.RE
.SH "ЗНАЧЕННЯ ВИХОДУ"
.PP
Якщо виконано успішно,
\fBsu\fR
повертає значення виходу виконаної команди\&.
.PP
Якщо цю команду перервано сигналом,
\fBsu\fR
повертає номер цього сигналу плюс 128\&.
.PP
Якщо su довелося перервати виконання команди (оскільки було надіслано команду щодо переривання роботи, але команда не перервала роботу вчасно),
\fBsu\fR
поверне 255\&.
.PP
Деякі значення виходу з
\fBsu\fR
є незалежними від виконаної команди:
.PP
\fI0\fR
.RS 4
успіх (лише
\fB\-\-help\fR)
.RE
.PP
\fI1\fR
.RS 4
Помилка системи або розпізнавання
.RE
.PP
\fI126\fR
.RS 4
Потрібну команду не знайдено
.RE
.PP
\fI127\fR
.RS 4
Потрібну команду не вдалося виконати
.RE
.SH "ДИВ\&. ТАКОЖ"
.PP
\fBlogin\fR(1),
\fBlogin.defs\fR(5),
\fBsg\fR(1),
\fBsh\fR(1)\&.
