'\" t
.\"     Title: gshadow
.\"    Author: Nicolas Fran\(,cois <nicolas.francois@centraliens.net>
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/11/2022
.\"    Manual: Формати файлів і файли налаштувань
.\"    Source: shadow-utils 4.13
.\"  Language: Ukrainian
.\"
.TH "gshadow" "5" "08/11/2022" "shadow\-utils 4\&.13" "Формати файлів і файли налашту"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
gshadow \- файл зашифрованих груп
.SH "ОПИС"
.PP
/etc/gshadow
містить зашифровані відомості щодо облікових записів груп\&.
.PP
Цей файл має бути недоступним для читання звичайними користувачами, якщо ви хочете підтримувати захист паролів\&.
.PP
У кожному рядку цього файла містяться такі відокремлені двокрапками поля:
.PP
\fBназва групи\fR
.RS 4
Це має бути коректна назва групи, яка існує у системі\&.
.RE
.PP
\fBшифрований пароль\fR
.RS 4
Зверніться до
\fBcrypt\fR(3), щоб дізнатися більше про те, як буде оброблено цей рядок\&.
.sp
Якщо у полі пароля міститься якийсь рядок, який не є коректним результатом виконання
\fBcrypt\fR(3), наприклад, ! або *, користувачі не зможуть скористатися паролем unix для доступу до групи (але учасники групи пароля не потребуватимуть)\&.
.sp
Пароль використовуватиметься, коли користувач, який не є учасником групи, захоче отримати права доступу до цієї групи (див\&.
\fBnewgrp\fR(1))\&.
.sp
Це поле може бути порожнім\&. Якщо поле є порожнім, лише учасники групи зможуть отримувати права доступу групи\&.
.sp
Поле пароля, яке починається зі знаку оклику, означає, що пароль заблоковано\&. Решта символів у рядку є вмістом поля пароля до того, як пароль було заблоковано\&.
.sp
Цей пароль має пріоритет над будь\-яким паролем, який вказано у
/etc/group\&.
.RE
.PP
\fBадміністратори\fR
.RS 4
Це має бути список відокремлених комами імен користувачів\&.
.sp
Адміністратори можуть змінювати пароль або учасників групи\&.
.sp
Також адміністратори мають ті самі права доступу, що і учасники (див\&. нижче)\&.
.RE
.PP
\fBучасники\fR
.RS 4
Це має бути список відокремлених комами імен користувачів\&.
.sp
Учасники можуть отримувати доступ до групи без надсилання запиту щодо пароля\&.
.sp
Вам слід використовувати той самий список користувачів, що і у
/etc/group\&.
.RE
.SH "ФАЙЛИ"
.PP
/etc/group
.RS 4
Відомості щодо груп облікових записів\&.
.RE
.PP
/etc/gshadow
.RS 4
Відомості щодо захищених груп облікових записів\&.
.RE
.SH "ДИВ\&. ТАКОЖ"
.PP
\fBgpasswd\fR(5),
\fBгрупа\fR(5),
\fBgrpck\fR(8),
\fBgrpconv\fR(8),
\fBnewgrp\fR(1)\&.
