'\" t
.\"     Title: passwd
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/11/2022
.\"    Manual: Формати файлів і файли налаштувань
.\"    Source: shadow-utils 4.13
.\"  Language: Ukrainian
.\"
.TH "passwd" "5" "08/11/2022" "shadow\-utils 4\&.13" "Формати файлів і файли налашту"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
passwd \- файл паролів
.SH "ОПИС"
.PP
/etc/passwd
містить по одному рядку для кожного з облікових записів користувача із сімома полями, які відокремлено двокрапками (\(Fo:\(Fc)\&. Цими полями є такі:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
ім\*(Aqя користувача
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
необов\*(Aqязковий шифрований пароль
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
числовий ідентифікатор користувача
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
числовий ідентифікатор групи
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
поле імені користувача або коментаря
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
домашній каталог користувача
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
необов\*(Aqязковий інтерпретатор команд користувача
.RE
.PP
Якщо у полі
\fIпароль\fR
міститься
\(Fox\(Fc
у нижньому регістрі, зашифрований пароль насправді зберігається у файлі
\fBshadow\fR(5);
\fIмає\fR
бути відповідний рядок у файлі
/etc/shadow, інакше обліковий запис користувача буде некоректним\&.
.PP
Поле, у якому зберігається зашифрований
\fIпароль\fR, може бути порожнім\&. Якщо пароль є порожнім, для розпізнавання за вказаним іменем користувача не потрібен буде пароль\&. Втім, деякі програми, які читають дані з файла
/etc/passwd, можуть взагалі вирішити не дозволити
\fIдовільний\fR
доступ, якщо поле
\fIпароль\fR
є порожнім\&.
.PP
Поле
\fIпароль\fR, яке починається зі знаку оклику, означає, що пароль заблоковано\&. Решта символів у рядку є вмістом поля
\fIпароль\fR
до того, як пароль було заблоковано\&.
.PP
Зверніться до
\fBcrypt\fR(3), щоб дізнатися більше про те, як буде оброблено цей рядок\&.
.PP
Якщо у полі пароля міститься якийсь рядок, який не є коректним результатом виконання
\fBcrypt\fR(3), наприклад, ! або *, користувач не зможе скористатися паролем unix для входу до облікового запису (але користувач зможе увійти до системи в інший спосіб)\&.
.PP
Поле коментаря, також відоме як поле gecos, використовують різноманітні загальносистемні інструменти, зокрема
\fBfinger\fR(1)\&. Амперсанд у цьому полі буде замінено записаним великим літерами іменем користувача, коли поле буде використано або показано у таких загальносистемних інструментах\&.
.PP
Поле домашнього каталогу задає назву початкового робочого каталогу\&. Програма
\fBlogin\fR
використовує ці дані для встановлення значення змінної середовища
\fB$HOME\fR\&.
.PP
Поле інтерпретатора команд задає назву командного інтерпретатора мови програмування користувача або назву початкової програми для виконання\&. Програма
\fBlogin\fR
використовує ці дані для встановлення значення змінної середовища
\fB$SHELL\fR\&. Якщо значення у цьому полі є порожнім, типовим його значенням буде значення
/bin/sh\&.
.SH "ФАЙЛИ"
.PP
/etc/passwd
.RS 4
Відомості щодо облікових записів користувача\&.
.RE
.PP
/etc/shadow
.RS 4
необов\*(Aqязковий файл шифрованих паролів
.RE
.PP
/etc/passwd\-
.RS 4
Резервна копію файла /etc/passwd\&.
.sp
Зауважте, що цей файл буде використано інструментами комплексу засобів shadow, але не усіма засобами керування записами користувачів і паролями\&.
.RE
.SH "ДИВ\&. ТАКОЖ"
.PP
\fBcrypt\fR(3),
\fBgetent\fR(1),
\fBgetpwnam\fR(3),
\fBlogin\fR(1),
\fBpasswd\fR(1),
\fBpwck\fR(8),
\fBpwconv\fR(8),
\fBpwunconv\fR(8),
\fBshadow\fR(5),
\fBsu\fR(1),
\fBsulogin\fR(8)\&.
