'\" t
.\"     Title: porttime
.\"    Author: Julianne Frances Haugh
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/11/2022
.\"    Manual: Формати файлів і файли налаштувань
.\"    Source: shadow-utils 4.13
.\"  Language: Ukrainian
.\"
.TH "porttime" "5" "08/11/2022" "shadow\-utils 4\&.13" "Формати файлів і файли налашту"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
porttime \- файл часу доступу до портів
.SH "ОПИС"
.PP
\fIporttime\fR
містить список пристроїв терміналів, імен користувачів та даних щодо дозволеного часу входу до системи\&.
.PP
Кожен запис складається з трьох відокремлених двокрапками полів\&. Перше поле є списком відокремлених комами пристроїв tty або зірочкою на позначення, що цьому запису відповідають усі пристрої tty\&. Друге поле є списком відокремлених комами імен користувачів або зірочкою на позначення, що цьому запису відповідають усі імена користувачів\&. Третє поле є списком відокремлених комами дозволених часів доступу\&.
.PP
Кожен запис часу доступу складається з нуля або більшої кількості скорочених записів днів тижня:
\fISu\fR,
\fIMo\fR,
\fITu\fR,
\fIWe\fR,
\fITh\fR,
\fIFr\fR
і
\fISa\fR, після яких вказано проміжок часу з двох значень, які відокремлено дефісом\&. Можна скористатися скороченням
\fIWk\fR
для позначення часу від понеділка до п\*(Aqятниці і скороченням
\fIAl\fR
для позначення будь\-якого дня\&. Якщо дні не вказано, буде використано
\fIAl\fR\&.
.SH "ПРИКЛАДИ"
.PP
Вказаний нижче запис дозволяє доступ до користувача
\fBjfh\fR
на будь\-якому порту протягом робочого тижня з 9 ранку до 5 вечора\&.
.PP
*:jfh:Wk0900\-1700
.PP
Вказані нижче записи дозволяють доступ лише до користувачів
\fIroot\fR
і
\fIoper\fR
на
/dev/console
будь\-коли\&. Цей приклад ілюструє спосіб, у який файл
/etc/porttime
є упорядкованим списком часів доступу\&. Другому запису відповідає будь\-який інший користувач, якому буде заборонено доступ будь\-коли\&.
.sp
.if n \{\
.RS 4
.\}
.nf
console:root,oper:Al0000\-2400 console:*:
.fi
.if n \{\
.RE
.\}
.PP
Наведений нижче запис дозволяє доступ для користувача
\fIgames\fR
до будь\-якого порту у неробочий час\&.
.PP
*:games:Wk1700\-0900,SaSu0000\-2400
.SH "ФАЙЛИ"
.PP
/etc/porttime
.RS 4
Файл, у якому містяться дані доступу до портів\&.
.RE
.SH "ДИВ\&. ТАКОЖ"
.PP
\fBlogin\fR(1)\&.
