'\" t
.\"     Title: suauth
.\"    Author: Marek Micha\(/lkiewicz
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 08/11/2022
.\"    Manual: Формати файлів і файли налаштувань
.\"    Source: shadow-utils 4.13
.\"  Language: Ukrainian
.\"
.TH "suauth" "5" "08/11/2022" "shadow\-utils 4\&.13" "Формати файлів і файли налашту"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "НАЗВА"
suauth \- докладний файл керування su
.SH "КОРОТКИЙ ОГЛЯД"
.HP \w'\fB/etc/suauth\fR\ 'u
\fB/etc/suauth\fR
.SH "ОПИС"
.PP
Файл
/etc/suauth
буде використано під час кожного виклику su\&. Він може змінити поведінку команди su на основі таких даних:
.sp
.if n \{\
.RS 4
.\}
.nf
1) користувача призначення su
.fi
.if n \{\
.RE
.\}
.PP
2) користувача, від імені якого віддано команду su (або будь\-яких груп, учасником яких він є)
.PP
Форматування файла описано нижче\&. Рядки, які починаються з символу #, вважатимуться коментарями\&. Такі рядки буде проігноровано;
.sp
.if n \{\
.RS 4
.\}
.nf
ідентифікатор\-призначення:похідний\-ідентифікатор:ДІЯ
.fi
.if n \{\
.RE
.\}
.PP
Де \(Foідентифікатор\-призначення\(Fc є словом
\fIALL\fR, списком відокремлених \(Fo,\(Fc імен користувачів або словами
\fIALL EXCEPT\fR, після яких вказано список відокремлених \(Fo,\(Fc імен користувачів\&.
.PP
Форматування запису \(Foпохідний\-ідентифікатор\(Fc є таким самим, що і для запису \(Foідентифікатор\-призначення\(Fc, окрім розпізнавання додаткового слова
\fIGROUP\fR\&. Можна також без проблем користуватися
\fIALL EXCEPT GROUP\fR\&. Після
\fIGROUP\fR
можна вказати назви однієї або декількох груп, відокремлених \(Fo,\(Fc\&. Ідентифікатора основної групи відповідної групи недостатньо, потрібен запис у
\fB/etc/group\fR(5)\&.
.PP
Дією може бути лише один із наведених нижче підтримуваних у поточній версії варіантів\&.
.PP
\fIDENY\fR
.RS 4
Спробу su буде зупинено навіть до того, як буде надіслано запит щодо пароля\&.
.RE
.PP
\fINOPASS\fR
.RS 4
Спроба виконати su автоматично успішна; запит щодо пароля не виконуватиметься\&.
.RE
.PP
\fIOWNPASS\fR
.RS 4
Для успішного виконання команди su користувач має ввести власний пароль\&. Програма попросить його це зробити\&.
.RE
.PP
Зауважте, що передбачено три окремих поля, які відокремлено двокрапками\&. Ніяких пробілів навколо двокрапок не повинно бути\&. Також зауважте, що файл буде оброблено рядок за рядком\&. Бдуе використано перше придатне правило без вивчення решти\&. Це уможливлює для адміністратора встановлення бажаного рівня керування доступом\&.
.SH "ПРИКЛАД"
.sp
.if n \{\
.RS 4
.\}
.nf
# приклад файла /etc/suauth
#
# Двійко привілейованих користувачів можуть
# виконувати su до root із власним паролем\&.
#
root:chris,birddog:OWNPASS
#
# Усі інші не можуть виконувати su до root, якщо
# не у групі wheel\&. Так роблять у BSD\&.
#
root:ALL EXCEPT GROUP wheel:DENY
#
# Можливо, облікові записи terry і birddog належать
# одній особі\&.
# Можна налаштувати доступ між ними
# без пароля\&.
#
terry:birddog:NOPASS birddog:terry:NOPASS
#
.fi
.if n \{\
.RE
.\}
.SH "ФАЙЛИ"
.PP
/etc/suauth
.RS 4
.RE
.SH "ВАДИ"
.PP
Може бути доволі багато проблем\&. Зокрема, обробник файла не пробачає синтаксичних помилок, не дає додавати пробіли у довільні місця (окрім початку і кінця рядків) і має специфічні правила щодо розмежування записів\&.
.SH "ДІАГНОСТИКА"
.PP
Про помилку при обробці файла буде повідомлено за допомогою
\fBsyslogd\fR(8)
у формі рівня ERR для можливості AUTH\&.
.SH "ДИВ\&. ТАКОЖ"
.PP
\fBsu\fR(1)\&.
